package gaia

import "fmt"
import "github.com/aporeto-inc/elemental"

import "github.com/aporeto-inc/gaia/golang/constants"

// ImageIdentity represents the Identity of the object
var ImageIdentity = elemental.Identity{
	Name:     "image",
	Category: "images",
}

// ImagesList represents a list of Images
type ImagesList []*Image

// Image represents the model of a image
type Image struct {
	// ID is the identifier of the object.
	ID string `json:"ID" cql:"-"`

	// AssociatedTags are the list of tags attached to an entity
	AssociatedTags []string `json:"associatedTags" cql:"associatedtags,omitempty"`

	// Name is the name of the entity
	Name string `json:"name" cql:"name,primarykey,omitempty"`

	// Registry refers to the service that stores images
	Registry string `json:"registry" cql:"registry,primarykey,omitempty"`

	// Repository is the name of the image repository
	Repository string `json:"repository" cql:"-"`

	// Tag is the tag of the image
	Tag string `json:"tag" cql:"tag,primarykey,omitempty"`

	// Vulnerability defines the security vulnerabiility level of the image
	Vulnerability constants.Vulnerability `json:"vulnerability" cql:"vulnerability,omitempty"`
}

// NewImage returns a new *Image
func NewImage() *Image {

	return &Image{}
}

// Identity returns the Identity of the object.
func (o *Image) Identity() elemental.Identity {

	return ImageIdentity
}

// Identifier returns the value of the object's unique identifier.
func (o *Image) Identifier() string {

	return o.ID
}

func (o *Image) String() string {

	return fmt.Sprintf("<%s:%s>", o.Identity().Name, o.Identifier())
}

// SetIdentifier sets the value of the object's unique identifier.
func (o *Image) SetIdentifier(ID string) {

	o.ID = ID
}

// GetAssociatedTags returns the associatedTags of the receiver
func (o *Image) GetAssociatedTags() []string {
	return o.AssociatedTags
}

// SetAssociatedTags set the given associatedTags of the receiver
func (o *Image) SetAssociatedTags(associatedTags []string) {
	o.AssociatedTags = associatedTags
}

// GetName returns the name of the receiver
func (o *Image) GetName() string {
	return o.Name
}

// Validate valides the current information stored into the structure.
func (o *Image) Validate() elemental.Errors {

	errors := elemental.Errors{}

	if err := elemental.ValidateRequiredString("name", o.Name); err != nil {
		errors = append(errors, err)
	}

	if err := elemental.ValidateRequiredString("registry", o.Registry); err != nil {
		errors = append(errors, err)
	}

	if err := elemental.ValidateRequiredString("tag", o.Tag); err != nil {
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (o Image) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	return ImageAttributesMap[name]
}

// ImageAttributesMap represents the map of attribute for Image.
var ImageAttributesMap = map[string]elemental.AttributeSpecification{
	"ID": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		ReadOnly:       true,
		Type:           "string",
		Unique:         true,
	},
	"AssociatedTags": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Getter:         true,
		Name:           "associatedTags",
		Setter:         true,
		Stored:         true,
		SubType:        "tags_list",
		Type:           "external",
	},
	"Name": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Getter:         true,
		Name:           "name",
		Orderable:      true,
		PrimaryKey:     true,
		ReadOnly:       true,
		Required:       true,
		Stored:         true,
		Type:           "string",
		Unique:         true,
	},
	"Registry": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		CreationOnly:   true,
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Name:           "registry",
		Orderable:      true,
		PrimaryKey:     true,
		ReadOnly:       true,
		Required:       true,
		Stored:         true,
		Type:           "string",
		Unique:         true,
	},
	"Repository": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		CreationOnly:   true,
		Exposed:        true,
		Format:         "free",
		Name:           "repository",
		Orderable:      true,
		ReadOnly:       true,
		Type:           "string",
		Unique:         true,
	},
	"Tag": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		CreationOnly:   true,
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Name:           "tag",
		Orderable:      true,
		PrimaryKey:     true,
		Required:       true,
		Stored:         true,
		Type:           "string",
		Unique:         true,
	},
	"Vulnerability": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		CreationOnly:   true,
		Exposed:        true,
		Name:           "vulnerability",
		ReadOnly:       true,
		Required:       true,
		Stored:         true,
		SubType:        "vulnerability_level",
		Type:           "external",
	},
}
