package gaia

import "fmt"
import "github.com/aporeto-inc/elemental"

import "time"

// NotificationIdentity represents the Identity of the object
var NotificationIdentity = elemental.Identity{
	Name:     "notification",
	Category: "notifications",
}

// NotificationsList represents a list of Notifications
type NotificationsList []*Notification

// Notification represents the model of a notification
type Notification struct {
	// ID is the identifier of the object.
	ID string `json:"ID" cql:"-"`

	// CreatedAt is the time when then notification was created
	CreatedAt string `json:"createdAt" cql:"createdat,omitempty"`

	// DeletedAt is the time when the notification was deleted
	DeletedAt time.Time `json:"deletedAt" cql:"deletedat,omitempty"`

	// Limit is the number of layers returned in notification
	LayerLimit int `json:"layerLimit" cql:"layerlimit,omitempty"`

	// Name is the name of the notification
	Name string `json:"name" cql:"name,omitempty"`

	// New is the new layers that introduced vulnerability
	New *VulnerabilityWithLayers `json:"new" cql:"new,omitempty"`

	// NextPage is the next page number
	NextPage string `json:"nextPage" cql:"nextpage,omitempty"`

	// NorifiedAt is the time when the notification was sent
	NotifiedAt time.Time `json:"notifiedAt" cql:"notifiedat,omitempty"`

	// Old is the old layers that introduced vulnerability
	Old *VulnerabilityWithLayers `json:"old" cql:"old,omitempty"`

	// Page is the page number
	Page string `json:"page" cql:"page,omitempty"`
}

// NewNotification returns a new *Notification
func NewNotification() *Notification {

	return &Notification{}
}

// Identity returns the Identity of the object.
func (o *Notification) Identity() elemental.Identity {

	return NotificationIdentity
}

// Identifier returns the value of the object's unique identifier.
func (o *Notification) Identifier() string {

	return o.ID
}

func (o *Notification) String() string {

	return fmt.Sprintf("<%s:%s>", o.Identity().Name, o.Identifier())
}

// SetIdentifier sets the value of the object's unique identifier.
func (o *Notification) SetIdentifier(ID string) {

	o.ID = ID
}

// Validate valides the current information stored into the structure.
func (o *Notification) Validate() elemental.Errors {

	errors := elemental.Errors{}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (o Notification) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	return NotificationAttributesMap[name]
}

// NotificationAttributesMap represents the map of attribute for Notification.
var NotificationAttributesMap = map[string]elemental.AttributeSpecification{
	"ID": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		ReadOnly:       true,
		Type:           "string",
		Unique:         true,
	},
	"CreatedAt": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Name:           "createdAt",
		Orderable:      true,
		Stored:         true,
		Type:           "string",
	},
	"DeletedAt": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Filterable:     true,
		Name:           "deletedAt",
		Orderable:      true,
		Stored:         true,
		Type:           "time",
	},
	"LayerLimit": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Filterable:     true,
		Name:           "layerLimit",
		Orderable:      true,
		Stored:         true,
		Type:           "integer",
	},
	"Name": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Name:           "name",
		Orderable:      true,
		Stored:         true,
		Type:           "string",
	},
	"New": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Filterable:     true,
		Name:           "new",
		Orderable:      true,
		Stored:         true,
		SubType:        "vulnerabilitylayers",
		Type:           "external",
	},
	"NextPage": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Name:           "nextPage",
		Orderable:      true,
		Stored:         true,
		Type:           "string",
	},
	"NotifiedAt": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Filterable:     true,
		Name:           "notifiedAt",
		Orderable:      true,
		Stored:         true,
		Type:           "time",
	},
	"Old": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Filterable:     true,
		Name:           "old",
		Orderable:      true,
		Stored:         true,
		SubType:        "vulnerabilitylayers",
		Type:           "external",
	},
	"Page": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Name:           "page",
		Orderable:      true,
		Stored:         true,
		Type:           "string",
	},
}
