package gaia

import "fmt"
import "github.com/aporeto-inc/elemental"

// PolicyRuleIdentity represents the Identity of the object
var PolicyRuleIdentity = elemental.Identity{
	Name:     "policyrule",
	Category: "policyrules",
}

// PolicyRulesList represents a list of PolicyRules
type PolicyRulesList []*PolicyRule

// PolicyRule represents the model of a policyrule
type PolicyRule struct {
	// ID is the identifier of the object.
	ID string `json:"ID" cql:"-" bson:"-"`

	// Action defines set of actions that must be enforced when a dependency is met.
	Action map[string]map[string]string `json:"action" cql:"-" bson:"-"`

	// Policy target networks
	Files FilePathsList `json:"files" cql:"-" bson:"-"`

	// Name is the name of the entity
	Name string `json:"name" cql:"name,omitempty" bson:"name"`

	// Policy target networks
	Namespaces NamespacesList `json:"namespaces" cql:"-" bson:"-"`

	// Policy target networks
	Networks ExternalServicesList `json:"networks" cql:"-" bson:"-"`

	// Propagated indicates if the policy is propagated.
	Propagated bool `json:"propagated" cql:"-" bson:"-"`

	// Relation describes the required operation to be performed between subjects and objects
	Relation []string `json:"relation" cql:"-" bson:"-"`

	// ServerProfiles provides the information about the server profile.
	Serverprofiles ServerProfilesList `json:"serverprofiles" cql:"-" bson:"-"`

	// Policy target networks
	Syscalls SystemCallsList `json:"syscalls" cql:"-" bson:"-"`

	// Policy target tags
	Tagclauses [][]string `json:"tagclauses" cql:"-" bson:"-"`
}

// NewPolicyRule returns a new *PolicyRule
func NewPolicyRule() *PolicyRule {

	return &PolicyRule{}
}

// Identity returns the Identity of the object.
func (o *PolicyRule) Identity() elemental.Identity {

	return PolicyRuleIdentity
}

// Identifier returns the value of the object's unique identifier.
func (o *PolicyRule) Identifier() string {

	return o.ID
}

// SetIdentifier sets the value of the object's unique identifier.
func (o *PolicyRule) SetIdentifier(ID string) {

	o.ID = ID
}

func (o *PolicyRule) String() string {

	return fmt.Sprintf("<%s:%s>", o.Identity().Name, o.Identifier())
}

// GetName returns the name of the receiver
func (o *PolicyRule) GetName() string {
	return o.Name
}

// SetName set the given name of the receiver
func (o *PolicyRule) SetName(name string) {
	o.Name = name
}

// Validate valides the current information stored into the structure.
func (o *PolicyRule) Validate() error {

	errors := elemental.Errors{}
	requiredErrors := elemental.Errors{}

	if err := elemental.ValidateRequiredString("name", o.Name); err != nil {
		requiredErrors = append(requiredErrors, err)
	}

	if err := elemental.ValidateRequiredString("name", o.Name); err != nil {
		errors = append(errors, err)
	}

	if len(requiredErrors) > 0 {
		return requiredErrors
	}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (PolicyRule) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	return PolicyRuleAttributesMap[name]
}

// AttributeSpecifications returns the full attribute specifications map.
func (PolicyRule) AttributeSpecifications() map[string]elemental.AttributeSpecification {

	return PolicyRuleAttributesMap
}

// PolicyRuleAttributesMap represents the map of attribute for PolicyRule.
var PolicyRuleAttributesMap = map[string]elemental.AttributeSpecification{
	"ID": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		Description:    `ID is the identifier of the object.`,
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		ReadOnly:       true,
		Type:           "string",
		Unique:         true,
	},
	"Action": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Description:    `Action defines set of actions that must be enforced when a dependency is met.`,
		Exposed:        true,
		Name:           "action",
		SubType:        "actions_list",
		Type:           "external",
	},
	"Files": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Description:    `Policy target networks `,
		Exposed:        true,
		Name:           "files",
		SubType:        "file_entities",
		Type:           "external",
	},
	"Name": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Description:    `Name is the name of the entity`,
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Getter:         true,
		Name:           "name",
		Orderable:      true,
		Required:       true,
		Setter:         true,
		Stored:         true,
		Type:           "string",
		Unique:         true,
	},
	"Namespaces": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Description:    `Policy target networks `,
		Exposed:        true,
		Name:           "namespaces",
		SubType:        "namespace_entities",
		Type:           "external",
	},
	"Networks": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Description:    `Policy target networks `,
		Exposed:        true,
		Name:           "networks",
		SubType:        "network_entities",
		Type:           "external",
	},
	"Propagated": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Description:    `Propagated indicates if the policy is propagated.`,
		Exposed:        true,
		Name:           "propagated",
		Type:           "boolean",
	},
	"Relation": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Description:    `Relation describes the required operation to be performed between subjects and objects`,
		Exposed:        true,
		Name:           "relation",
		SubType:        "relations_list",
		Type:           "external",
	},
	"Serverprofiles": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Description:    `ServerProfiles provides the information about the server profile.`,
		Exposed:        true,
		Name:           "serverprofiles",
		SubType:        "serverprofile_entities",
		Type:           "external",
	},
	"Syscalls": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Description:    `Policy target networks `,
		Exposed:        true,
		Name:           "syscalls",
		SubType:        "syscall_entities",
		Type:           "external",
	},
	"Tagclauses": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Description:    `Policy target tags`,
		Exposed:        true,
		Name:           "tagclauses",
		SubType:        "target_tags",
		Type:           "external",
	},
}
