package gaia

import "fmt"
import "github.com/aporeto-inc/elemental"

// SystemInfoStatusValue represents the possible values for attribute "status".
type SystemInfoStatusValue string

const (
	// SystemInfoStatusDegraded represents the value Degraded.
	SystemInfoStatusDegraded SystemInfoStatusValue = "Degraded"

	// SystemInfoStatusFailure represents the value Failure.
	SystemInfoStatusFailure SystemInfoStatusValue = "Failure"

	// SystemInfoStatusOk represents the value Ok.
	SystemInfoStatusOk SystemInfoStatusValue = "Ok"
)

// SystemInfoIdentity represents the Identity of the object
var SystemInfoIdentity = elemental.Identity{
	Name:     "systeminfo",
	Category: "systeminfos",
}

// SystemInfosList represents a list of SystemInfos
type SystemInfosList []*SystemInfo

// SystemInfo represents the model of a systeminfo
type SystemInfo struct {
	// APIVersion is the API version served by the server.
	APIVersion string `json:"APIVersion" cql:"-" bson:"-"`

	// BahamutVersion is the version of Bahamut used by the server.
	BahamutVersion string `json:"bahamutVersion" cql:"-" bson:"-"`

	// ElementalVersion is the version of Elemental used by the server.
	ElementalVersion string `json:"elementalVersion" cql:"-" bson:"-"`

	// GaiaVersion is the version of Gaia used by the server.
	GaiaVersion string `json:"gaiaVersion" cql:"-" bson:"-"`

	// ManipulateVersion is the version of Manipulate used by the server.
	ManipulateVersion string `json:"manipulateVersion" cql:"manipulateversion,omitempty" bson:"manipulateversion"`

	// MidgardURL contains the url to use to obtain a token.
	MidgardURL string `json:"midgardURL" cql:"midgardurl,omitempty" bson:"midgardurl"`

	// SquallVersion is the version of server.
	SquallVersion string `json:"squallVersion" cql:"-" bson:"-"`

	// Status is the overall health status of the server.
	Status SystemInfoStatusValue `json:"status" cql:"-" bson:"-"`
}

// NewSystemInfo returns a new *SystemInfo
func NewSystemInfo() *SystemInfo {

	return &SystemInfo{}
}

// Identity returns the Identity of the object.
func (o *SystemInfo) Identity() elemental.Identity {

	return SystemInfoIdentity
}

// Identifier returns the value of the object's unique identifier.
func (o *SystemInfo) Identifier() string {

	return ""
}

func (o *SystemInfo) String() string {

	return fmt.Sprintf("<%s:%s>", o.Identity().Name, o.Identifier())
}

// SetIdentifier sets the value of the object's unique identifier.
func (o *SystemInfo) SetIdentifier(ID string) {

}

// Validate valides the current information stored into the structure.
func (o *SystemInfo) Validate() elemental.Errors {

	errors := elemental.Errors{}

	if err := elemental.ValidateStringInList("status", string(o.Status), []string{"Degraded", "Failure", "Ok"}, true); err != nil {
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (o SystemInfo) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	return SystemInfoAttributesMap[name]
}

// SystemInfoAttributesMap represents the map of attribute for SystemInfo.
var SystemInfoAttributesMap = map[string]elemental.AttributeSpecification{
	"APIVersion": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Name:           "APIVersion",
		Orderable:      true,
		ReadOnly:       true,
		Type:           "string",
	},
	"BahamutVersion": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Name:           "bahamutVersion",
		Orderable:      true,
		ReadOnly:       true,
		Type:           "string",
	},
	"ElementalVersion": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Name:           "elementalVersion",
		Orderable:      true,
		ReadOnly:       true,
		Type:           "string",
	},
	"GaiaVersion": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Name:           "gaiaVersion",
		Orderable:      true,
		ReadOnly:       true,
		Type:           "string",
	},
	"ManipulateVersion": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Name:           "manipulateVersion",
		Orderable:      true,
		Stored:         true,
		Type:           "string",
	},
	"MidgardURL": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Name:           "midgardURL",
		Orderable:      true,
		Stored:         true,
		Type:           "string",
	},
	"SquallVersion": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Name:           "squallVersion",
		Orderable:      true,
		ReadOnly:       true,
		Type:           "string",
	},
	"Status": elemental.AttributeSpecification{
		AllowedChoices: []string{"Degraded", "Failure", "Ok"},
		Autogenerated:  true,
		Exposed:        true,
		Filterable:     true,
		Name:           "status",
		Orderable:      true,
		ReadOnly:       true,
		Type:           "enum",
	},
}
