package gaia

import "fmt"
import "github.com/aporeto-inc/elemental"

const (
	MyNamespaceAttributeNameID         elemental.AttributeSpecificationNameKey = "mynamespace/ID"
	MyNamespaceAttributeNameNamespaces elemental.AttributeSpecificationNameKey = "mynamespace/namespaces"
)

// MyNamespaceIdentity represents the Identity of the object
var MyNamespaceIdentity = elemental.Identity{
	Name:     "mynamespace",
	Category: "mynamespaces",
}

// MyNamespacesList represents a list of MyNamespaces
type MyNamespacesList []*MyNamespace

// MyNamespace represents the model of a mynamespace
type MyNamespace struct {
	ID         string        `json:"ID,omitempty" cql:"-"`
	Namespaces []interface{} `json:"namespaces,omitempty" cql:"-"`
}

// NewMyNamespace returns a new *MyNamespace
func NewMyNamespace() *MyNamespace {

	return &MyNamespace{}
}

// Identity returns the Identity of the object.
func (o *MyNamespace) Identity() elemental.Identity {

	return MyNamespaceIdentity
}

// Identifier returns the value of the object's unique identifier.
func (o *MyNamespace) Identifier() string {

	return o.ID
}

func (o *MyNamespace) String() string {

	return fmt.Sprintf("<%s:%s>", o.Identity().Name, o.Identifier())
}

// SetIdentifier sets the value of the object's unique identifier.
func (o *MyNamespace) SetIdentifier(ID string) {

	o.ID = ID
}

// Validate valides the current information stored into the structure.
func (o *MyNamespace) Validate() elemental.Errors {

	errors := elemental.Errors{}

	return errors
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (o MyNamespace) SpecificationForAttribute(name elemental.AttributeSpecificationNameKey) elemental.AttributeSpecification {

	return MyNamespaceAttributesMap[name]
}

var MyNamespaceAttributesMap = map[elemental.AttributeSpecificationNameKey]elemental.AttributeSpecification{
	MyNamespaceAttributeNameID: elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		Type:           "string",
		Unique:         true,
	},
	MyNamespaceAttributeNameNamespaces: elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Name:           "namespaces",
		Orderable:      true,
		SubType:        "namespaces_list",
		Type:           "external",
	},
}
