package gaia

import "fmt"
import "github.com/aporeto-inc/elemental"

const (
	// PolicyRuleAttributeNameID represents the attribute ID.
	PolicyRuleAttributeNameID elemental.AttributeSpecificationNameKey = "policyrule/ID"

	// PolicyRuleAttributeNameAction represents the attribute action.
	PolicyRuleAttributeNameAction elemental.AttributeSpecificationNameKey = "policyrule/action"

	// PolicyRuleAttributeNameFiles represents the attribute files.
	PolicyRuleAttributeNameFiles elemental.AttributeSpecificationNameKey = "policyrule/files"

	// PolicyRuleAttributeNameNamespaces represents the attribute namespaces.
	PolicyRuleAttributeNameNamespaces elemental.AttributeSpecificationNameKey = "policyrule/namespaces"

	// PolicyRuleAttributeNameNetworks represents the attribute networks.
	PolicyRuleAttributeNameNetworks elemental.AttributeSpecificationNameKey = "policyrule/networks"

	// PolicyRuleAttributeNameRelation represents the attribute relation.
	PolicyRuleAttributeNameRelation elemental.AttributeSpecificationNameKey = "policyrule/relation"

	// PolicyRuleAttributeNameSyscalls represents the attribute syscalls.
	PolicyRuleAttributeNameSyscalls elemental.AttributeSpecificationNameKey = "policyrule/syscalls"

	// PolicyRuleAttributeNameTagclauses represents the attribute tagclauses.
	PolicyRuleAttributeNameTagclauses elemental.AttributeSpecificationNameKey = "policyrule/tagclauses"
)

// PolicyRuleIdentity represents the Identity of the object
var PolicyRuleIdentity = elemental.Identity{
	Name:     "policyrule",
	Category: "policyrules",
}

// PolicyRulesList represents a list of PolicyRules
type PolicyRulesList []*PolicyRule

// PolicyRule represents the model of a policyrule
type PolicyRule struct {
	// ID is the identifier of the object.
	ID string `json:"ID,omitempty" cql:"-"`

	// Action defines set of actions that must be enforced when a dependency is met.
	Action map[string]map[string]string `json:"action,omitempty" cql:"action,omitempty"`

	// Policy target networks
	Files FilePathsList `json:"files,omitempty" cql:"files,omitempty"`

	// Policy target networks
	Namespaces NamespacesList `json:"namespaces,omitempty" cql:"namespaces,omitempty"`

	// Policy target networks
	Networks ExternalServicesList `json:"networks,omitempty" cql:"networks,omitempty"`

	// Relation describes the required operation to be performed between subjects and objects
	Relation []string `json:"relation,omitempty" cql:"relation,omitempty"`

	// Policy target networks
	Syscalls SystemCallsList `json:"syscalls,omitempty" cql:"syscalls,omitempty"`

	// Policy target tags
	Tagclauses [][]string `json:"tagclauses,omitempty" cql:"tagclauses,omitempty"`
}

// NewPolicyRule returns a new *PolicyRule
func NewPolicyRule() *PolicyRule {

	return &PolicyRule{}
}

// Identity returns the Identity of the object.
func (o *PolicyRule) Identity() elemental.Identity {

	return PolicyRuleIdentity
}

// Identifier returns the value of the object's unique identifier.
func (o *PolicyRule) Identifier() string {

	return o.ID
}

func (o *PolicyRule) String() string {

	return fmt.Sprintf("<%s:%s>", o.Identity().Name, o.Identifier())
}

// SetIdentifier sets the value of the object's unique identifier.
func (o *PolicyRule) SetIdentifier(ID string) {

	o.ID = ID
}

// Validate valides the current information stored into the structure.
func (o *PolicyRule) Validate() elemental.Errors {

	errors := elemental.Errors{}

	return errors
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (o PolicyRule) SpecificationForAttribute(name elemental.AttributeSpecificationNameKey) elemental.AttributeSpecification {

	return PolicyRuleAttributesMap[name]
}

// PolicyRuleAttributesMap represents the map of attribute for PolicyRule.
var PolicyRuleAttributesMap = map[elemental.AttributeSpecificationNameKey]elemental.AttributeSpecification{
	PolicyRuleAttributeNameID: elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		Type:           "string",
		Unique:         true,
	},
	PolicyRuleAttributeNameAction: elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Name:           "action",
		Stored:         true,
		SubType:        "actions_list",
		Type:           "external",
	},
	PolicyRuleAttributeNameFiles: elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Name:           "files",
		Stored:         true,
		SubType:        "file_entities",
		Type:           "external",
	},
	PolicyRuleAttributeNameNamespaces: elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Name:           "namespaces",
		Stored:         true,
		SubType:        "namespace_entities",
		Type:           "external",
	},
	PolicyRuleAttributeNameNetworks: elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Name:           "networks",
		Stored:         true,
		SubType:        "network_entities",
		Type:           "external",
	},
	PolicyRuleAttributeNameRelation: elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Name:           "relation",
		Stored:         true,
		SubType:        "relations_list",
		Type:           "external",
	},
	PolicyRuleAttributeNameSyscalls: elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Name:           "syscalls",
		Stored:         true,
		SubType:        "syscall_entities",
		Type:           "external",
	},
	PolicyRuleAttributeNameTagclauses: elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Name:           "tagclauses",
		Stored:         true,
		SubType:        "target_tags",
		Type:           "external",
	},
}
