package gaia

import "github.com/aporeto-inc/elemental"

const (
	PolicyRuleAttributeNameID         elemental.AttributeSpecificationNameKey = "policyrule/ID"
	PolicyRuleAttributeNameAction     elemental.AttributeSpecificationNameKey = "policyrule/action"
	PolicyRuleAttributeNameFiles      elemental.AttributeSpecificationNameKey = "policyrule/files"
	PolicyRuleAttributeNameNamespaces elemental.AttributeSpecificationNameKey = "policyrule/namespaces"
	PolicyRuleAttributeNameNetworks   elemental.AttributeSpecificationNameKey = "policyrule/networks"
	PolicyRuleAttributeNameRelation   elemental.AttributeSpecificationNameKey = "policyrule/relation"
	PolicyRuleAttributeNameSyscalls   elemental.AttributeSpecificationNameKey = "policyrule/syscalls"
	PolicyRuleAttributeNameTagclauses elemental.AttributeSpecificationNameKey = "policyrule/tagclauses"
)

// PolicyRuleIdentity represents the Identity of the object
var PolicyRuleIdentity = elemental.Identity{
	Name:     "policyrule",
	Category: "policyrules",
}

// PolicyRulesList represents a list of PolicyRules
type PolicyRulesList []*PolicyRule

// PolicyRule represents the model of a policyrule
type PolicyRule struct {
	ID         string                       `json:"-" cql:"-"`
	Action     map[string]map[string]string `json:"action,omitempty" cql:"action,omitempty"`
	Files      FilePathsList                `json:"files,omitempty" cql:"files,omitempty"`
	Namespaces NamespacesList               `json:"namespaces,omitempty" cql:"namespaces,omitempty"`
	Networks   ExternalServicesList         `json:"networks,omitempty" cql:"networks,omitempty"`
	Relation   []string                     `json:"relation,omitempty" cql:"relation,omitempty"`
	Syscalls   SystemCallsList              `json:"syscalls,omitempty" cql:"syscalls,omitempty"`
	Tagclauses [][]string                   `json:"tagclauses,omitempty" cql:"tagclauses,omitempty"`
}

// NewPolicyRule returns a new *PolicyRule
func NewPolicyRule() *PolicyRule {

	return &PolicyRule{}
}

// Identity returns the Identity of the object.
func (o *PolicyRule) Identity() elemental.Identity {

	return PolicyRuleIdentity
}

// Identifier returns the value of the object's unique identifier.
func (o *PolicyRule) Identifier() string {

	return o.ID
}

// SetIdentifier sets the value of the object's unique identifier.
func (o *PolicyRule) SetIdentifier(ID string) {

	o.ID = ID
}

// Validate valides the current information stored into the structure.
func (o *PolicyRule) Validate() elemental.Errors {

	errors := elemental.Errors{}

	return errors
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (o PolicyRule) SpecificationForAttribute(name elemental.AttributeSpecificationNameKey) elemental.AttributeSpecification {

	return PolicyRuleAttributesMap[name]
}

var PolicyRuleAttributesMap = map[elemental.AttributeSpecificationNameKey]elemental.AttributeSpecification{
	PolicyRuleAttributeNameID: elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		CreationOnly:   true,
		Format:         "free",
		Identifier:     true,
		Name:           "ID",
		Type:           "string",
		Unique:         true,
	},
	PolicyRuleAttributeNameAction: elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Name:           "action",
		Stored:         true,
		SubType:        "action_list",
		Type:           "external",
	},
	PolicyRuleAttributeNameFiles: elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Name:           "files",
		Stored:         true,
		SubType:        "file_entities",
		Type:           "external",
	},
	PolicyRuleAttributeNameNamespaces: elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Name:           "namespaces",
		Stored:         true,
		SubType:        "namespace_entities",
		Type:           "external",
	},
	PolicyRuleAttributeNameNetworks: elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Name:           "networks",
		Stored:         true,
		SubType:        "network_entities",
		Type:           "external",
	},
	PolicyRuleAttributeNameRelation: elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Name:           "relation",
		Stored:         true,
		SubType:        "relation_list",
		Type:           "external",
	},
	PolicyRuleAttributeNameSyscalls: elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Name:           "syscalls",
		Stored:         true,
		SubType:        "syscall_entities",
		Type:           "external",
	},
	PolicyRuleAttributeNameTagclauses: elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Name:           "tagclauses",
		Stored:         true,
		SubType:        "target_tags",
		Type:           "external",
	},
}
