package gaia

import "fmt"
import "github.com/aporeto-inc/elemental"

// RenderedPoliciesIdentity represents the Identity of the object
var RenderedPoliciesIdentity = elemental.Identity{
	Name:     "renderedpolicies",
	Category: "renderedpolicies",
}

// RenderedPoliciesList represents a list of RenderedPolicies
type RenderedPoliciesList []*RenderedPolicies

// RenderedPolicies represents the model of a renderedpolicies
type RenderedPolicies struct {
	// ID is the identifier of the object.
	ID string `json:"ID,omitempty" cql:"-"`

	// EgressPolicies lists all the egress policies attached to ProcessingUnit
	EgressPolicies map[string][]PolicyRule `json:"egressPolicies,omitempty" cql:"-"`

	// IngressPolicies lists all the ingress policies attached to ProcessingUnit
	IngressPolicies map[string][]PolicyRule `json:"ingressPolicies,omitempty" cql:"-"`

	// Identifier of the ProcessingUnit
	ProcessingUnitID string `json:"processingUnitID,omitempty" cql:"-"`
}

// NewRenderedPolicies returns a new *RenderedPolicies
func NewRenderedPolicies() *RenderedPolicies {

	return &RenderedPolicies{}
}

// Identity returns the Identity of the object.
func (o *RenderedPolicies) Identity() elemental.Identity {

	return RenderedPoliciesIdentity
}

// Identifier returns the value of the object's unique identifier.
func (o *RenderedPolicies) Identifier() string {

	return o.ProcessingUnitID
}

func (o *RenderedPolicies) String() string {

	return fmt.Sprintf("<%s:%s>", o.Identity().Name, o.Identifier())
}

// SetIdentifier sets the value of the object's unique identifier.
func (o *RenderedPolicies) SetIdentifier(ID string) {

	o.ProcessingUnitID = ID
}

// Validate valides the current information stored into the structure.
func (o *RenderedPolicies) Validate() elemental.Errors {

	errors := elemental.Errors{}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (o RenderedPolicies) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	return RenderedPoliciesAttributesMap[name]
}

// RenderedPoliciesAttributesMap represents the map of attribute for RenderedPolicies.
var RenderedPoliciesAttributesMap = map[string]elemental.AttributeSpecification{
	"ID": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		Type:           "string",
		Unique:         true,
	},
	"EgressPolicies": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Name:           "egressPolicies",
		Orderable:      true,
		SubType:        "rendered_policy",
		Type:           "external",
	},
	"IngressPolicies": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Name:           "ingressPolicies",
		Orderable:      true,
		SubType:        "rendered_policy",
		Type:           "external",
	},
	"ProcessingUnitID": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		CreationOnly:   true,
		Exposed:        true,
		Format:         "free",
		Identifier:     true,
		Name:           "processingUnitID",
		Type:           "string",
		Unique:         true,
	},
}
