{
    "attributes": [
        {
            "allowed_chars": null,
            "allowed_choices": null,
            "autogenerated": null,
            "channel": null,
            "creation_only": null,
            "default_order": null,
            "default_value": null,
            "deprecated": null,
            "description": "Array of netowrk access policies computed",
            "exposed": true,
            "filterable": false,
            "foreign_key": null,
            "format": null,
            "getter": null,
            "identifier": null,
            "index": null,
            "max_length": null,
            "max_value": null,
            "min_length": null,
            "min_value": null,
            "name": "networkAccessPolicies",
            "orderable": true,
            "primary_key": null,
            "read_only": null,
            "required": null,
            "secret": false,
            "setter": null,
            "stored": true,
            "subtype": "network_access_policies_list",
            "transient": false,
            "type": "external",
            "unique": null,
            "uniqueScope": null
        }
    ],
    "children": [],
    "model": {
        "aliases": [],
        "create": null,
        "delete": false,
        "description": "[nodoc]",
        "entity_name": "ComputedPolicy",
        "extends": [
            "@identifiable-nopk-nostored"
        ],
        "get": true,
        "package": "Platform",
        "resource_name": "computedpolicies",
        "rest_name": "computedpolicy",
        "root": null,
        "update": false
    }
}