{
    "attributes": [
        {
            "allowed_chars": null,
            "allowed_choices": null,
            "autogenerated": null,
            "channel": null,
            "creation_only": null,
            "default_order": null,
            "default_value": null,
            "deprecated": null,
            "description": "externalService contains the associated external service information",
            "exposed": true,
            "filterable": true,
            "foreign_key": null,
            "format": "free",
            "getter": null,
            "identifier": null,
            "index": null,
            "max_length": null,
            "max_value": null,
            "min_length": null,
            "min_value": null,
            "name": "externalService",
            "orderable": true,
            "primary_key": null,
            "read_only": null,
            "required": null,
            "secret": null,
            "setter": null,
            "stored": true,
            "subtype": null,
            "transient": null,
            "type": "string",
            "unique": null,
            "uniqueScope": null
        }
    ],
    "children": [],
    "model": {
        "aliases": [
            "extac",
            "extacs"
        ],
        "create": null,
        "delete": false,
        "description": "ExternalAccess allows to retrieve connection from or to an external service",
        "entity_name": "ExternalAccess",
        "extends": [],
        "get": true,
        "package": null,
        "resource_name": "externalaccesses",
        "rest_name": "externalaccess",
        "root": null,
        "update": false
    }
}