{
    "attributes": [
        {
            "allowed_chars": null,
            "allowed_choices": null,
            "autogenerated": null,
            "channel": null,
            "creation_only": null,
            "default_order": null,
            "default_value": null,
            "deprecated": null,
            "description": "Subject contains the subject of the Quota Policy.",
            "exposed": true,
            "filterable": true,
            "foreign_key": null,
            "format": null,
            "getter": null,
            "identifier": null,
            "index": null,
            "max_length": null,
            "max_value": null,
            "min_length": null,
            "min_value": null,
            "name": "subject",
            "orderable": true,
            "primary_key": null,
            "read_only": null,
            "required": true,
            "secret": null,
            "setter": null,
            "stored": true,
            "subtype": "policies_list",
            "transient": null,
            "type": "external",
            "unique": null,
            "uniqueScope": null
        }
    ],
    "children": [],
    "model": {
        "aliases": [
            "quotapols",
            "quotapol",
            "quotas",
            "quota"
        ],
        "create": null,
        "delete": true,
        "description": "Quotas Policies allows to set quotas on the number of objects that can be created in a namespace.",
        "entity_name": "QuotaPolicy",
        "extends": [
            "@base",
            "@described",
            "@disabled",
            "@identifiable-nopk-nostored",
            "@metadatable",
            "@named",
            "@propagated"
        ],
        "get": true,
        "package": "Policy",
        "resource_name": "quotapolicies",
        "rest_name": "quotapolicy",
        "root": null,
        "update": true
    }
}