package vincemodels

import "fmt"
import "github.com/aporeto-inc/elemental"

import "sync"

import "time"

// KubernetesclusterIdentity represents the Identity of the object
var KubernetesclusterIdentity = elemental.Identity{
	Name:     "kubernetescluster",
	Category: "kubernetesclusters",
}

// KubernetesclustersList represents a list of Kubernetesclusters
type KubernetesclustersList []*Kubernetescluster

// ContentIdentity returns the identity of the objects in the list.
func (o KubernetesclustersList) ContentIdentity() elemental.Identity {

	return KubernetesclusterIdentity
}

// List converts the object to an elemental.IdentifiablesList.
func (o KubernetesclustersList) List() elemental.IdentifiablesList {

	out := elemental.IdentifiablesList{}
	for _, item := range o {
		out = append(out, item)
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o KubernetesclustersList) DefaultOrder() []string {

	return []string{}
}

// Kubernetescluster represents the model of a kubernetescluster
type Kubernetescluster struct {
	// ID of the object.
	ID string `json:"ID" bson:"_id"`

	// Link to the certificate created in Vince for this cluster
	CertificateID string `json:"certificateID" bson:"certificateid"`

	// createdAt represents the creation date of the object.
	CreateTime time.Time `json:"createTime" bson:"createtime"`

	// base64 of the .tar.gz file that contains all the .YAMLs files needed to create the aporeto side on your kubernetes Cluster
	KubernetesDefinitions string `json:"kubernetesDefinitions" bson:"-"`

	// The name of your cluster
	Name string `json:"name" bson:"name"`

	// Link to your namespace
	NamespaceID string `json:"namespaceID" bson:"namespaceid"`

	// None
	ParentID string `json:"parentID" bson:"parentid"`

	// None
	TargetNetworks []string `json:"targetNetworks" bson:"targetnetworks"`

	// UpdateTime represents the last update date of the objct.
	UpdateTime time.Time `json:"updateTime" bson:"updatetime"`

	ModelVersion float64 `json:"-" bson:"_modelversion"`

	sync.Mutex
}

// NewKubernetescluster returns a new *Kubernetescluster
func NewKubernetescluster() *Kubernetescluster {

	return &Kubernetescluster{
		ModelVersion: 1.0,
	}
}

// Identity returns the Identity of the object.
func (o *Kubernetescluster) Identity() elemental.Identity {

	return KubernetesclusterIdentity
}

// Identifier returns the value of the object's unique identifier.
func (o *Kubernetescluster) Identifier() string {

	return o.ID
}

// SetIdentifier sets the value of the object's unique identifier.
func (o *Kubernetescluster) SetIdentifier(ID string) {

	o.ID = ID
}

// Version returns the hardcoded version of the model
func (o *Kubernetescluster) Version() float64 {

	return 1.0
}

// DefaultOrder returns the list of default ordering fields.
func (o *Kubernetescluster) DefaultOrder() []string {

	return []string{}
}

func (o *Kubernetescluster) String() string {

	return fmt.Sprintf("<%s:%s>", o.Identity().Name, o.Identifier())
}

// Validate valides the current information stored into the structure.
func (o *Kubernetescluster) Validate() error {

	errors := elemental.Errors{}
	requiredErrors := elemental.Errors{}

	if len(requiredErrors) > 0 {
		return requiredErrors
	}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (*Kubernetescluster) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	if v, ok := KubernetesclusterAttributesMap[name]; ok {
		return v
	}

	// We could not find it, so let's check on the lower case indexed spec map
	return KubernetesclusterLowerCaseAttributesMap[name]
}

// AttributeSpecifications returns the full attribute specifications map.
func (*Kubernetescluster) AttributeSpecifications() map[string]elemental.AttributeSpecification {

	return KubernetesclusterAttributesMap
}

// KubernetesclusterAttributesMap represents the map of attribute for Kubernetescluster.
var KubernetesclusterAttributesMap = map[string]elemental.AttributeSpecification{
	"ID": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		Description:    `ID of the object.`,
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		PrimaryKey:     true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"CertificateID": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Description:    `Link to the certificate created in Vince for this cluster `,
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Name:           "certificateID",
		Orderable:      true,
		Stored:         true,
		Type:           "string",
		Unique:         true,
	},
	"CreateTime": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		Description:    `createdAt represents the creation date of the object.`,
		Exposed:        true,
		Filterable:     true,
		Name:           "createTime",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "time",
	},
	"KubernetesDefinitions": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Description:    `base64 of the .tar.gz file that contains all the .YAMLs files needed to create the aporeto side on your kubernetes Cluster`,
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Name:           "kubernetesDefinitions",
		Orderable:      true,
		Type:           "string",
	},
	"Name": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Description:    `The name of your cluster`,
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Name:           "name",
		Orderable:      true,
		Stored:         true,
		Type:           "string",
	},
	"NamespaceID": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Description:    `Link to your namespace `,
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Name:           "namespaceID",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"ParentID": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Name:           "parentID",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"TargetNetworks": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Filterable:     true,
		Name:           "targetNetworks",
		Orderable:      true,
		Stored:         true,
		SubType:        "target_networks_list",
		Type:           "external",
	},
	"UpdateTime": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		Description:    `UpdateTime represents the last update date of the objct.`,
		Exposed:        true,
		Filterable:     true,
		Name:           "updateTime",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "time",
	},
}

// KubernetesclusterLowerCaseAttributesMap represents the map of attribute for Kubernetescluster.
var KubernetesclusterLowerCaseAttributesMap = map[string]elemental.AttributeSpecification{
	"id": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		Description:    `ID of the object.`,
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Identifier:     true,
		Name:           "ID",
		Orderable:      true,
		PrimaryKey:     true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"certificateid": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Description:    `Link to the certificate created in Vince for this cluster `,
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Name:           "certificateID",
		Orderable:      true,
		Stored:         true,
		Type:           "string",
		Unique:         true,
	},
	"createtime": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		Description:    `createdAt represents the creation date of the object.`,
		Exposed:        true,
		Filterable:     true,
		Name:           "createTime",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "time",
	},
	"kubernetesdefinitions": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Description:    `base64 of the .tar.gz file that contains all the .YAMLs files needed to create the aporeto side on your kubernetes Cluster`,
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Name:           "kubernetesDefinitions",
		Orderable:      true,
		Type:           "string",
	},
	"name": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Description:    `The name of your cluster`,
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Name:           "name",
		Orderable:      true,
		Stored:         true,
		Type:           "string",
	},
	"namespaceid": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Description:    `Link to your namespace `,
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Name:           "namespaceID",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"parentid": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Filterable:     true,
		Format:         "free",
		Name:           "parentID",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "string",
	},
	"targetnetworks": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Exposed:        true,
		Filterable:     true,
		Name:           "targetNetworks",
		Orderable:      true,
		Stored:         true,
		SubType:        "target_networks_list",
		Type:           "external",
	},
	"updatetime": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		Description:    `UpdateTime represents the last update date of the objct.`,
		Exposed:        true,
		Filterable:     true,
		Name:           "updateTime",
		Orderable:      true,
		ReadOnly:       true,
		Stored:         true,
		Type:           "time",
	},
}
