{
    "attributes": [
        {
            "autogenerated": true,
            "description": "Claims of the user who performed the operation.",
            "exposed": true,
            "filterable": true,
            "name": "claims",
            "orderable": true,
            "read_only": true,
            "stored": true,
            "subtype": "raw_data",
            "type": "external"
        },
        {
            "autogenerated": true,
            "description": "Data of the notification.",
            "exposed": true,
            "filterable": true,
            "name": "data",
            "orderable": true,
            "read_only": true,
            "stored": true,
            "subtype": "raw_data",
            "type": "external"
        },
        {
            "autogenerated": true,
            "description": "Date of the notification.",
            "exposed": true,
            "filterable": true,
            "name": "date",
            "orderable": true,
            "read_only": true,
            "stored": true,
            "type": "time"
        },
        {
            "autogenerated": true,
            "description": "Error contains the eventual error.",
            "exposed": true,
            "name": "error",
            "orderable": true,
            "read_only": true,
            "stored": true,
            "subtype": "raw_data",
            "type": "external"
        },
        {
            "description": "Message of the notification.",
            "exposed": true,
            "filterable": true,
            "format": "free",
            "name": "message",
            "orderable": true,
            "stored": true,
            "type": "string"
        },
        {
            "autogenerated": true,
            "description": "Namespace of the notification.",
            "exposed": true,
            "filterable": true,
            "format": "free",
            "name": "namespace",
            "orderable": true,
            "read_only": true,
            "stored": true,
            "type": "string"
        },
        {
            "autogenerated": true,
            "description": "Operation describe what kind of operation the notification represents.",
            "exposed": true,
            "filterable": true,
            "format": "free",
            "name": "operation",
            "read_only": true,
            "stored": true,
            "type": "string"
        },
        {
            "autogenerated": true,
            "description": "OriginalData contains the eventual original data of the object that has been modified.",
            "exposed": true,
            "filterable": true,
            "name": "originalData",
            "orderable": true,
            "read_only": true,
            "stored": true,
            "subtype": "raw_data",
            "type": "external"
        },
        {
            "autogenerated": true,
            "description": "Source contains meta information about the source.",
            "exposed": true,
            "filterable": true,
            "format": "free",
            "name": "source",
            "orderable": true,
            "read_only": true,
            "stored": true,
            "type": "string"
        },
        {
            "autogenerated": true,
            "description": "TargetIdentity is the Identity of the related object.",
            "exposed": true,
            "filterable": true,
            "format": "free",
            "name": "targetIdentity",
            "orderable": true,
            "read_only": true,
            "stored": true,
            "type": "string"
        }
    ],
    "model": {
        "get": true,
        "description": "Contains all the activity log that happened in a namespace. All successful or failed actions will be available, and eventual errors as well as the claims of the user who triggered the actiions. This log is capped and only keeps the last 50k entries by default. ",
        "entity_name": "Activity",
        "extends": [
            "@identifiable-pk-stored"
        ],
        "package": "squall",
        "resource_name": "activities",
        "rest_name": "activity"
    }
}
