attributes:
- description: Action contains the code that will be executed if the condition is
    met.
  exposed: true
  name: actions
  required: true
  stored: true
  subtype: string
  type: list
- description: Condition contains the code that will be executed to decide if any
    action should be taken.
  exposed: true
  format: free
  name: condition
  required: true
  stored: true
  type: string
- description: Entitlements declares which operations are allowed on which identities.
  exposed: true
  name: entitlements
  stored: true
  subtype: automation_entitlements
  type: external
- autogenerated: true
  description: Error contains the eventual error of the last run.
  exposed: true
  name: errors
  read_only: true
  stored: true
  subtype: string
  type: list
- description: Events contains the identity and operation an event must have to trigger
    the automation
  exposed: true
  name: events
  stored: true
  subtype: automation_events
  type: external
- autogenerated: true
  description: LastExecTime holds the last successful execution tine.
  exposed: true
  name: lastExecTime
  read_only: true
  stored: true
  type: time
- description: Parameters are passed to the functions.
  exposed: true
  name: parameters
  stored: true
  subtype: automation_parameters
  type: external
- description: Schedule tells when to run the automation. Must be a valid CRON format.
    This only applies if the trigger is set to Time.
  exposed: true
  format: free
  name: schedule
  stored: true
  type: string
- autogenerated: true
  description: Stdout contains the last run standard output.
  exposed: true
  format: free
  name: stdout
  read_only: true
  stored: true
  type: string
- autogenerated: true
  creation_only: true
  description: Token holds the unique access token used as a password to trigger the
    authentication. It will be visible only after creation.
  exposed: true
  format: free
  name: token
  secret: true
  stored: true
  type: string
- description: If set to true a new token will be issued, and the previous one invalidated.
  exposed: true
  name: tokenRenew
  type: boolean
- allowed_choices:
  - Event
  - RemoteCall
  - Time
  default_value: Time
  description: Trigger controls when the automation should be triggered.
  exposed: true
  filterable: true
  name: trigger
  orderable: true
  stored: true
  type: enum
children:
- rest_name: trigger
  get: true
  create: true
model:
  aliases:
  - autos
  - auto
  delete: true
  get: true
  update: true
  entity_name: Automation
  extends:
  - '@base'
  - '@described'
  - '@disabled'
  - '@identifiable-pk-stored'
  - '@named'
  package: sephiroth
  resource_name: automations
  rest_name: automation
