# Model
model:
  rest_name: awsaccount
  resource_name: awsaccounts
  entity_name: AWSAccount
  package: vince
  description: |-
    Allows to bind an AWS account to your Aporeto account to allow auto registration
    of enforcers running on EC2.
  aliases:
  - aws
  - awsaccs
  - awsacc
  get: true
  delete: true
  extends:
  - '@identifiable-pk-stored'
  - '@timeable'

# Attributes
attributes:
- name: accessKeyID
  description: |-
    AccessKeyID contains the aws access key ID. This is used to retrieve your
    account id, and it is not stored.
  type: string
  exposed: true
  required: true
  creation_only: true
  example_value: aws access key id
  format: free

- name: accessToken
  description: |-
    AccessToken contains your aws access token. It is used to retrieve your account
    id, and it not stored.
  type: string
  exposed: true
  creation_only: true
  format: free

- name: accountID
  description: accountID contains your verified accound id.
  type: string
  exposed: true
  stored: true
  read_only: true
  autogenerated: true
  filterable: true
  format: free
  orderable: true

- name: parentID
  description: ParentID contains the parent Vince account ID.
  type: string
  exposed: true
  stored: true
  read_only: true
  autogenerated: true
  filterable: true
  format: free

- name: parentName
  description: ParentName contains the name of the Vince parent Account.
  type: string
  exposed: true
  stored: true
  read_only: true
  autogenerated: true
  filterable: true
  format: free

- name: region
  description: Region contains your the region where your AWS account is located.
  type: string
  exposed: true
  stored: true
  required: true
  creation_only: true
  example_value: us-west-2
  filterable: true
  format: free
  orderable: true

- name: secretAccessKey
  description: |-
    secretAccessKey contains the secret key. It is used to retrieve your account id,
    and it is not stored.
  type: string
  exposed: true
  required: true
  creation_only: true
  example_value: aws secret access key
  format: free
