# Model
model:
  rest_name: export
  resource_name: export
  entity_name: Export
  package: squall
  description: Export the policies and related objects in a given namespace.

# Attributes
attributes:
- name: APIVersion
  description: APIVersion of the api used for the exported data.
  type: integer
  exposed: true
  read_only: true
  autogenerated: true

- name: auditProfiles
  description: List of all exported audit profiles.
  type: external
  exposed: true
  subtype: exported_data_content
  read_only: true
  autogenerated: true

- name: externalServices
  description: List of exported external services.
  type: external
  exposed: true
  subtype: exported_data_content
  read_only: true
  autogenerated: true

- name: fileAccessPolicies
  description: List of exported file access policies.
  type: external
  exposed: true
  subtype: exported_data_content
  read_only: true
  autogenerated: true

- name: filePaths
  description: List of exported file paths.
  type: external
  exposed: true
  subtype: exported_data_content
  read_only: true
  autogenerated: true

- name: isolationProfiles
  description: List of all exported isolation profiles.
  type: external
  exposed: true
  subtype: exported_data_content
  read_only: true
  autogenerated: true

- name: networkAccessPolicies
  description: List of exported network policies.
  type: external
  exposed: true
  subtype: exported_data_content
  read_only: true
  autogenerated: true

- name: processingUnitPolicies
  description: List of all exported processingUnitPolicies.
  type: external
  exposed: true
  subtype: exported_data_content
  autogenerated: true
