{
    "attributes": [
        {
            "allowed_chars": null,
            "allowed_choices": null,
            "autogenerated": true,
            "channel": null,
            "creation_only": null,
            "default_order": null,
            "default_value": null,
            "deprecated": null,
            "description": "IPRecords refers to a list of IPRecord that contains the IP information",
            "exposed": true,
            "filterable": false,
            "foreign_key": null,
            "format": null,
            "getter": null,
            "identifier": null,
            "index": null,
            "max_length": null,
            "max_value": null,
            "min_length": null,
            "min_value": null,
            "name": "IPRecords",
            "orderable": false,
            "primary_key": null,
            "read_only": true,
            "required": null,
            "secret": null,
            "setter": null,
            "stored": false,
            "subtype": "ip_records",
            "transient": null,
            "type": "external",
            "unique": null,
            "uniqueScope": null
        }
    ],
    "children": [],
    "model": {
        "aliases": [
            "extac",
            "extacs"
        ],
        "create": null,
        "delete": false,
        "description": "ExternalAccess allows to retrieve connection from or to an external service",
        "entity_name": "ExternalAccess",
        "extends": [],
        "get": false,
        "package": "squall",
        "resource_name": "externalaccesses",
        "rest_name": "externalaccess",
        "root": null,
        "update": false
    }
}
