attributes:
- autogenerated: true
  description: DataPoints is a list of time/value pairs that represent the flow events
    over time.
  exposed: true
  name: dataPoints
  read_only: true
  subtype: datapoints_list
  type: external
- autogenerated: true
  description: DestinationIDs is the IDs of the destination.
  exposed: true
  format: free
  name: destinationIDs
  read_only: true
  subtype: flowstatistic_origin_list
  type: external
- autogenerated: true
  description: DestinationTags contains the tags used to identify destination
  exposed: true
  name: destinationTags
  read_only: true
  subtype: selectors_list
  type: external
- allowed_choices:
  - Flows
  - Ports
  autogenerated: true
  default_value: Flows
  description: Metric is the kind of metric the statistic represents.
  exposed: true
  name: metric
  read_only: true
  type: enum
- allowed_choices:
  - Accepted
  - Any
  - Rejected
  autogenerated: true
  default_value: Accepted
  description: Mode defines if the metric is for accepted or rejected flows.
  exposed: true
  name: mode
  read_only: true
  type: enum
- autogenerated: true
  description: SourceIDs is the sources of the stats.
  exposed: true
  format: free
  name: sourceIDs
  read_only: true
  subtype: flowstatistic_origin_list
  type: external
- autogenerated: true
  description: 'SourceTags contains the tags used to identify the source. '
  exposed: true
  name: sourceTags
  read_only: true
  subtype: selectors_list
  type: external
- allowed_choices:
  - Repartition
  - Serie
  autogenerated: true
  default_value: Serie
  description: Type is the type of representation
  exposed: true
  name: type
  read_only: true
  type: enum
- autogenerated: true
  description: UserIdentifier can be set by the user as a query parameter. It will
    be returned in the FlowStatistic object.
  exposed: true
  format: free
  name: userIdentifier
  orderable: true
  type: string
model:
  aliases:
  - flowstat
  - flowstats
  description: Returns network access statistics on a particular processing unit or
    group of processing units based on their tags.
  entity_name: FlowStatistic
  extends:
  - '@identifiable-nopk-nostored'
  package: jenova
  resource_name: flowstatistics
  rest_name: flowstatistic
