# Model
model:
  rest_name: log
  resource_name: logs
  entity_name: Log
  package: highwind
  description: Retrieves the log of a deployed app.

# Attributes
attributes:
- name: data
  description: Data contains all logs data.
  type: external
  exposed: true
  subtype: logs
  read_only: true
  autogenerated: true
