attributes:
- description: EnforcerID is the ID of the enforcer associated with the processing
    unit
  exposed: true
  filterable: true
  format: free
  name: enforcerID
  stored: true
  type: string
- autogenerated: true
  description: LastSyncTime is the time when the policy was last resolved
  exposed: true
  name: lastSyncTime
  orderable: true
  stored: true
  type: time
- description: NativeContextID is the Docker UUID or service PID
  exposed: true
  filterable: true
  format: free
  name: nativeContextID
  stored: true
  type: string
- description: NetworkServices is the list of services that this processing unit has
    declared that it will be listening to. This can happen either with an activation
    command or by exposing the ports in a container manifest.
  exposed: true
  filterable: true
  name: networkServices
  orderable: true
  stored: true
  subtype: processing_unit_services_list
  type: external
- allowed_choices:
  - Initialized
  - Paused
  - Running
  - Stopped
  - Terminated
  default_value: Initialized
  description: OperationalStatus of the processing unit
  exposed: true
  filterable: true
  name: operationalStatus
  stored: true
  type: enum
- allowed_choices:
  - Docker
  - LinuxService
  - RKT
  - User
  creation_only: true
  description: Type of the container ecosystem
  exposed: true
  filterable: true
  name: type
  required: true
  stored: true
  type: enum
children:
- rest_name: apiservice
  get: true
- rest_name: fileaccess
  get: true
- rest_name: renderedpolicy
  get: true
- rest_name: vulnerability
  get: true
model:
  aliases:
  - pu
  - pus
  create: true
  delete: true
  get: true
  update: true
  description: A Processing Unit reprents anything that can compute. It can be a Docker
    container, or a simple Unix process. They are created, updated and deleted by
    the system as they come and go. You can only modify its tags.  Processing Units
    use Network Access Policies to define which other Processing Units or External
    Services they can communicate with and File Access Policies to define what File
    Paths they can use.
  entity_name: ProcessingUnit
  extends:
  - '@archivable'
  - '@base'
  - '@described'
  - '@identifiable-pk-stored'
  - '@metadatable'
  - '@named'
  package: squall
  resource_name: processingunits
  rest_name: processingunit
