{
    "attributes": [
        {
            "autogenerated": true,
            "description": "ID contains the ID of the revocation.",
            "format": "free",
            "identifier": true,
            "name": "ID",
            "primary_key": true,
            "read_only": true,
            "stored": true,
            "type": "string"
        },
        {
            "creation_only": true,
            "description": "Contains the certificate expiration date. This will be used to clean up revoked certificates that have expired.",
            "exposed": true,
            "name": "expirationDate",
            "stored": true,
            "type": "time"
        },
        {
            "description": "Set time from when the certificate will be revoked.",
            "exposed": true,
            "name": "revokeDate",
            "stored": true,
            "type": "time"
        },
        {
            "creation_only": true,
            "description": "SerialNumber of the revoked certificate.",
            "exposed": true,
            "format": "free",
            "name": "serialNumber",
            "stored": true,
            "type": "string"
        },
        {
            "creation_only": true,
            "description": "Subject of the certificate related to the revocation.",
            "exposed": true,
            "format": "free",
            "name": "subject",
            "stored": true,
            "type": "string"
        }
    ],
    "model": {
        "update": true,
        "description": "Used to revoke a certificate",
        "entity_name": "Revocation",
        "package": "barret",
        "resource_name": "revocations",
        "rest_name": "revocation"
    }
}
