{
    "attributes": [
        {
            "autogenerated": true,
            "description": "ID of the service",
            "exposed": true,
            "filterable": true,
            "format": "free",
            "identifier": true,
            "name": "ID",
            "primary_key": true,
            "read_only": true,
            "stored": true,
            "type": "string"
        },
        {
            "creation_only": true,
            "description": "AccountName represents the vince account name",
            "exposed": true,
            "format": "free",
            "name": "accountName",
            "stored": true,
            "type": "string"
        },
        {
            "description": "CategoryID of the service.",
            "exposed": true,
            "filterable": true,
            "format": "free",
            "name": "categoryID",
            "orderable": true,
            "read_only": true,
            "stored": true,
            "type": "string"
        },
        {
            "description": "K8SIdentifier retains the identifier for kubernetes.",
            "format": "free",
            "name": "k8sIdentifier",
            "stored": true,
            "type": "string"
        },
        {
            "creation_only": true,
            "description": "Name of the service",
            "exposed": true,
            "filterable": true,
            "format": "free",
            "name": "name",
            "orderable": true,
            "stored": true,
            "type": "string"
        },
        {
            "description": "Namespace in which the service in running.",
            "exposed": true,
            "filterable": true,
            "format": "free",
            "name": "namespace",
            "orderable": true,
            "stored": true,
            "type": "string"
        },
        {
            "description": "Parameters is a list of parameters to start the service",
            "exposed": true,
            "name": "parameters",
            "stored": true,
            "subtype": "service_parameters",
            "type": "external"
        },
        {
            "description": "RelatedObjects retains all objects created to use this service.",
            "name": "relatedObjects",
            "stored": true,
            "subtype": "service_relatedobjects",
            "type": "external"
        },
        {
            "description": "Replicas represents the number of replicas for the service.",
            "exposed": true,
            "name": "replicas",
            "stored": true,
            "type": "integer"
        },
        {
            "allowed_choices": [
                "Error",
                "Pending",
                "Running"
            ],
            "default_value": "Pending",
            "description": "Status of the service.",
            "exposed": true,
            "filterable": true,
            "name": "status",
            "orderable": true,
            "read_only": true,
            "stored": true,
            "type": "enum"
        }
    ],
    "children": [
        {
            "rest_name": "log",
            "get": true
        }
    ],
    "model": {
        "aliases": [
            "srv"
        ],
        "delete": true,
        "get": true,
        "update": true,
        "description": "Service represents a service that can be launched",
        "entity_name": "Service",
        "package": "highwind",
        "resource_name": "services",
        "rest_name": "service"
    }
}
