attributes:
- autogenerated: true
  description: Results contains the result of the query.
  exposed: true
  name: results
  read_only: true
  subtype: time_series_results
  type: external
model:
  aliases:
  - sq
  create: true
  description: StatsQuery is a generic API to retrieve time series data stored by
    the Aporeto system. The API allows different types of queries that are all protected
    within the namespace of the user.
  entity_name: StatsQuery
  package: jenova
  resource_name: statsqueries
  rest_name: statsquery
