{
    "attributes": [
        {
            "creation_only": true,
            "description": "CSR contains the Certificate Signing Request as a PEM encoded string.",
            "exposed": true,
            "format": "free",
            "name": "CSR",
            "required": true,
            "type": "string"
        },
        {
            "autogenerated": true,
            "description": "ID contains the identifier of the certificate.",
            "exposed": true,
            "filterable": true,
            "format": "free",
            "identifier": true,
            "name": "ID",
            "read_only": true,
            "type": "string"
        },
        {
            "autogenerated": true,
            "description": "Certificate contains the certificate data in PEM format.",
            "exposed": true,
            "format": "free",
            "name": "certificate",
            "read_only": true,
            "type": "string"
        },
        {
            "creation_only": true,
            "description": "ExpirationDate contains the requested expiration date.",
            "exposed": true,
            "name": "expirationDate",
            "subtype": "string",
            "type": "time"
        },
        {
            "creation_only": true,
            "description": "Extensions is a list of extensions that can be added as SAN extensions to the certificate.",
            "exposed": true,
            "name": "extensions",
            "subtype": "extensions_list",
            "type": "external"
        },
        {
            "allowed_choices": [
                "Public",
                "System"
            ],
            "default_value": "Public",
            "description": "Selects what CA should sign the certificate.",
            "exposed": true,
            "name": "signer",
            "type": "enum"
        },
        {
            "allowed_choices": [
                "Client",
                "Server",
                "ServerClient"
            ],
            "default_value": "Client",
            "description": "Usage defines the requested key usage.",
            "exposed": true,
            "filterable": true,
            "name": "usage",
            "orderable": true,
            "stored": true,
            "type": "enum"
        }
    ],
    "model": {
        "description": "This API allows to retrieve an client certifcate for api authentication.",
        "entity_name": "X509Certificate",
        "package": "barret",
        "resource_name": "x509certificates",
        "rest_name": "x509certificate",
        "private": true
    }
}
