# Model
model:
  rest_name: x509certificate
  resource_name: x509certificates
  entity_name: X509Certificate
  package: barret
  description: This API allows to retrieve an client certifcate for api authentication.
  private: true

# Attributes
attributes:
- name: CSR
  description: CSR contains the Certificate Signing Request as a PEM encoded string.
  type: string
  exposed: true
  required: true
  creation_only: true
  format: free

- name: ID
  description: ID contains the identifier of the certificate.
  type: string
  exposed: true
  read_only: true
  autogenerated: true
  filterable: true
  format: free
  identifier: true

- name: certificate
  description: Certificate contains the certificate data in PEM format.
  type: string
  exposed: true
  read_only: true
  autogenerated: true
  format: free

- name: expirationDate
  description: ExpirationDate contains the requested expiration date.
  type: time
  exposed: true
  subtype: string
  creation_only: true

- name: extensions
  description: |-
    Extensions is a list of extensions that can be added as SAN extensions to the
    certificate.
  type: external
  exposed: true
  subtype: extensions_list
  creation_only: true

- name: signer
  description: Selects what CA should sign the certificate.
  type: enum
  exposed: true
  allowed_choices:
  - Public
  - System
  default_value: Public

- name: usage
  description: Usage defines the requested key usage.
  type: enum
  exposed: true
  stored: true
  allowed_choices:
  - Client
  - Server
  - ServerClient
  default_value: Client
  filterable: true
  orderable: true
