# Model
model:
  rest_name: remotepingprobe
  resource_name: remotepingprobes
  entity_name: RemotePingProbe
  package: guy
  group: core/enforcer
  description: |-
    Represents information about a remote ping probe that is governed by a different
    set of permissions.
  detached: true

# Attributes
attributes:
  v1:
  - name: controllerID
    description: The controller ID that manages the ping report.
    type: string
    exposed: true
    stored: true
    read_only: true
    autogenerated: true
    omit_empty: true

  - name: namespace
    description: |-
      The namespace where the ping report is stored. Only applicable when the remote
      controller is empty.
    type: string
    exposed: true
    stored: true
    read_only: true
    autogenerated: true
    omit_empty: true

  - name: namespaceType
    description: |-
      Type of the namespace reported. It can be hash or plain, depending on various
      factors.
    type: enum
    exposed: true
    stored: true
    read_only: true
    allowed_choices:
    - Plain
    - Hash
    autogenerated: true

  - name: probeID
    description: The ID of the probe. Only applicable when the remote controller is
      empty.
    type: string
    exposed: true
    stored: true
    read_only: true
    autogenerated: true
    omit_empty: true
