# Model
model:
  rest_name: accountcheck
  resource_name: accountchecks
  entity_name: AccountCheck
  package: vince
  group: core/account
  description: Validates the password for an account.
  private: true

# Attributes
attributes:
  v1:
  - name: ID
    description: ID of the account if validated.
    type: string
    exposed: true
    read_only: true
    autogenerated: true

  - name: OTP
    description: eventual otp.
    type: string
    exposed: true

  - name: email
    description: email of the account if validated.
    type: string
    exposed: true
    read_only: true
    autogenerated: true

  - name: handle
    description: Account name of email.
    type: string
    exposed: true
    required: true
    example_value: acme

  - name: name
    description: name of the account.
    type: string
    exposed: true
    read_only: true
    autogenerated: true

  - name: password
    description: provided password.
    type: string
    exposed: true
    required: true
    example_value: S3cr3t#
