# Model
model:
  rest_name: activity
  resource_name: activities
  entity_name: Activity
  package: hojo
  group: core/monitoring
  description: |-
    Contains all the activity log that happened in a namespace. All successful or
    failed actions will be available, and eventual errors as well as the claims of
    the user who triggered the actiions. This log is capped and only keeps the last
    50k entries by default.
  get:
    description: Retrieves the object with the given ID.
  extends:
  - '@zoned'
  - '@identifiable-stored'
  - '@namespaced'

# Indexes
indexes:
- - namespace
  - date
- - namespace
  - operation
- - namespace
  - error.code
- - namespace
  - targetIdentity
- - namespace
  - data.ID
- - namespace
  - originalData.ID

# Attributes
attributes:
  v1:
  - name: claims
    description: Claims of the user who performed the operation.
    type: object
    exposed: true
    stored: true
    read_only: true
    autogenerated: true
    orderable: true

  - name: data
    description: Data of the notification.
    type: object
    exposed: true
    stored: true
    read_only: true
    autogenerated: true
    orderable: true

  - name: date
    description: Date of the notification.
    type: time
    exposed: true
    stored: true
    read_only: true
    autogenerated: true
    orderable: true

  - name: error
    description: Error contains the eventual error.
    type: object
    exposed: true
    stored: true
    read_only: true
    autogenerated: true
    orderable: true

  - name: message
    description: Message of the notification.
    type: string
    exposed: true
    stored: true
    orderable: true

  - name: operation
    description: Operation describe what kind of operation the notification represents.
    type: string
    exposed: true
    stored: true
    read_only: true
    autogenerated: true
    filterable: true

  - name: originalData
    description: |-
      OriginalData contains the eventual original data of the object that has been
      modified.
    type: object
    exposed: true
    stored: true
    read_only: true
    autogenerated: true
    orderable: true

  - name: source
    description: Source contains meta information about the source.
    type: string
    exposed: true
    stored: true
    read_only: true
    autogenerated: true
    filterable: true
    orderable: true

  - name: targetIdentity
    description: TargetIdentity is the Identity of the related object.
    type: string
    exposed: true
    stored: true
    read_only: true
    autogenerated: true
    filterable: true
    orderable: true
