# Model
model:
  rest_name: apicheck
  resource_name: apichecks
  entity_name: APICheck
  package: cid
  group: policy/authorization
  description: |-
    Allows you to verify if a client identified by his token is allowed to do
    some operations on some APIs.

# Attributes
attributes:
  v1:
  - name: authorized
    description: Contains the results of the check.
    type: external
    exposed: true
    subtype: map[string]bool
    read_only: true
    autogenerated: true

  - name: namespace
    description: The namespace to use to check the API authorization.
    type: string
    exposed: true
    required: true
    example_value: /namespace

  - name: operation
    description: The operation you want to check.
    type: enum
    exposed: true
    stored: true
    allowed_choices:
    - Create
    - Delete
    - Info
    - Patch
    - Retrieve
    - RetrieveMany
    - Update
    filterable: true
    orderable: true

  - name: targetIdentities
    description: |-
      Contains the list of identities you want to check the
      authorization of.
    type: list
    exposed: true
    subtype: string
    required: true
    example_value:
    - processingunit
    - enforcer
