# Model
model:
  rest_name: authz
  resource_name: authz
  entity_name: Authz
  package: cid
  group: core/authorization
  description: This is an internal api that is used to resolve to api authorization.
  private: true

# Attributes
attributes:
  v1:
  - name: claims
    description: The list of verified claims.
    type: list
    exposed: true
    subtype: string
    required: true
    example_value:
    - '@auth:account=acme'
    - '@auth:realm=vince'

  - name: clientIP
    description: IP of the client.
    type: string
    exposed: true

  - name: error
    description: Return an eventual error.
    type: string
    exposed: true
    read_only: true
    autogenerated: true
    omit_empty: true

  - name: permissions
    description: |-
      If the parameter permissions=1 is set, targetIdentity and targetOperation are
      ignored and this attribute will contain all the permission for the given claims.
    type: external
    exposed: true
    subtype: map[string]map[string]bool
    read_only: true
    autogenerated: true
    omit_empty: true

  - name: targetNamespace
    description: description.
    type: string
    exposed: true
    required: true
    example_value: /acme
