{
    "attributes": [
        {
            "allowed_chars": null,
            "allowed_choices": null,
            "autogenerated": null,
            "channel": null,
            "creation_only": null,
            "default_order": null,
            "default_value": null,
            "deprecated": null,
            "description": "Notification is the name of the notification sent by Clair using the webhook",
            "exposed": true,
            "filterable": true,
            "foreign_key": null,
            "format": null,
            "getter": null,
            "identifier": null,
            "index": null,
            "max_length": null,
            "max_value": null,
            "min_length": null,
            "min_value": null,
            "name": "notification",
            "orderable": true,
            "primary_key": null,
            "read_only": null,
            "required": null,
            "setter": null,
            "stored": false,
            "subtype": "notification",
            "transient": false,
            "type": "external",
            "unique": null,
            "uniqueScope": null
        }
    ],
    "children": [],
    "model": {
        "create": null,
        "delete": false,
        "description": null,
        "entity_name": "ClairNotification",
        "extends": [
            "@base",
            "@identifiable-pk-stored"
        ],
        "get": true,
        "package": "Infrastructure",
        "resource_name": "clairnotifications",
        "rest_name": "clairnotification",
        "root": null,
        "update": false
    }
}