# Model
model:
  rest_name: clausesmatch
  resource_name: clausesmatches
  entity_name: ClauseMatch
  package: squall
  group: core/policy
  description: |-
    This API allows to pass a set of tags and find the objects that would match the
    clause in a policy resolution.

# Attributes
attributes:
  v1:
  - name: clauses
    description: The tag clause to resolve.
    type: external
    exposed: true
    subtype: '[][]string'
    stored: true
    required: true
    example_value:
    - - color=blue
      - size=big
    - - color=red
    validations:
    - $tagsExpression

  - name: match
    description: Contains the matched objects.
    type: external
    exposed: true
    subtype: '[]map[string]interface{}'
    read_only: true
    autogenerated: true

  - name: targetIdentity
    description: The identity to render the clauses from.
    type: string
    exposed: true
    required: true
    example_value: processingunit
    validations:
    - $identity
