# Model
model:
  rest_name: datapathcertificate
  resource_name: datapathcertificates
  entity_name: DataPathCertificate
  package: squall
  group: core/processingunit
  description: |-
    Used by defender instances to retrieve various certificates used
    for the datapath.

# Attributes
attributes:
  v1:
  - name: CSR
    description: |-
      Contains the certificate signing request (CSR) the defender wants 
      Segment Console to sign. Depending on the certificate there will 
      be various requirements for the CSR to be accepted.
    type: string
    exposed: true
    required: true
    example_value: |-
      -----BEGIN CERTIFICATE REQUEST-----
      MIICvDCCAaQCAQAwdzELMAkGA1UEBhMCVVMxDTALBgNVBAgMBFV0YWgxDzANBgNV
      BAcMBkxpbmRvbjEWMBQGA1UECgwNRGlnaUNlcnQgSW5jLjERMA8GA1UECwwIRGln
      aUNlcnQxHTAbBgNVBAMMFGV4YW1wbGUuZGlnaWNlcnQuY29tMIIBIjANBgkqhkiG
      9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8+To7d+2kPWeBv/orU3LVbJwDrSQbeKamCmo
      wp5bqDxIwV20zqRb7APUOKYoVEFFOEQs6T6gImnIolhbiH6m4zgZ/CPvWBOkZc+c
      1Po2EmvBz+AD5sBdT5kzGQA6NbWyZGldxRthNLOs1efOhdnWFuhI162qmcflgpiI
      WDuwq4C9f+YkeJhNn9dF5+owm8cOQmDrV8NNdiTqin8q3qYAHHJRW28glJUCZkTZ
      wIaSR6crBQ8TbYNE0dc+Caa3DOIkz1EOsHWzTx+n0zKfqcbgXi4DJx+C1bjptYPR
      BPZL8DAeWuA8ebudVT44yEp82G96/Ggcf7F33xMxe0yc+Xa6owIDAQABoAAwDQYJ
      KoZIhvcNAQEFBQADggEBAB0kcrFccSmFDmxox0Ne01UIqSsDqHgL+XmHTXJwre6D
      hJSZwbvEtOK0G3+dr4Fs11WuUNt5qcLsx5a8uk4G6AKHMzuhLsJ7XZjgmQXGECpY
      Q4mC3yT3ZoCGpIXbw+iP3lmEEXgaQL0Tx5LFl/okKbKYwIqNiyKWOMj7ZR/wxWg/
      ZDGRs55xuoeLDJ/ZRFf9bI+IaCUd1YrfYcHIl3G87Av+r49YVwqRDT0VDV7uLgqn
      29XI1PpVUNCPQGn9p/eX6Qo7vpDaPybRtA2R7XLKjQaF9oXWeCUqy1hvJac9QFO2
      97Ob1alpHPoZ7mWiEuJwjBPii6a9M9G30nUo39lBi1w=
      -----END CERTIFICATE REQUEST-----

  - name: certificate
    description: The certificate.
    type: string
    exposed: true
    read_only: true
    autogenerated: true

  - name: objectID
    description: ID of the object you want to issue a certificate for.
    type: string
    exposed: true
    required: true
    example_value: 5c83035648675400019ab901

  - name: sessionID
    description: Provides the session ID of the defender when retrieving a datapath
      certificate.
    type: string
    exposed: true
    example_value: 5c83035648675400019ab901

  - name: signer
    description: Contains the CA that signed the delivered certificate.
    type: string
    exposed: true
    read_only: true
    autogenerated: true

  - name: token
    description: Contains a cryptographic token.
    type: string
    exposed: true
    read_only: true
    autogenerated: true

  - name: type
    description: Type of certificate.
    type: enum
    exposed: true
    allowed_choices:
    - Enforcer
    - Service
    - ServicePing
    example_value: Service
