# Model
model:
  rest_name: fileaccess
  resource_name: fileaccesses
  entity_name: FileAccess
  package: jenova
  description: Returns file access statistics on a particular processing unit.

# Attributes
attributes:
  v1:
  - name: action
    description: Action tells if the access has been allowed or not.
    type: string
    exposed: true
    read_only: true
    autogenerated: true
    format: free

  - name: count
    description: Count tells how many times the file has been accessed.
    type: integer
    exposed: true
    read_only: true
    autogenerated: true

  - name: host
    description: Host is the host that served the accessed file.
    type: string
    exposed: true
    read_only: true
    autogenerated: true
    format: free

  - name: mode
    description: Mode is the mode of the accessed file.
    type: enum
    exposed: true
    read_only: true
    allowed_choices:
    - Read
    - ReadWrite
    - Write
    autogenerated: true

  - name: path
    description: Path is the path of the accessed file.
    type: string
    exposed: true
    read_only: true
    autogenerated: true
    format: free

  - name: protocol
    description: Protocol is the protocol used to access the file.
    type: string
    exposed: true
    read_only: true
    autogenerated: true
    format: free
