# Model
model:
  rest_name: importreference
  resource_name: importreferences
  entity_name: ImportReference
  package: yuna
  group: core
  description: Allows you to import and keep a reference.
  aliases:
  - importref
  - impref
  get:
    description: Retrieves the object with the given ID.
  delete:
    description: Deletes the object with the given ID.
    global_parameters:
    - $filtering
  extends:
  - '@zoned'
  - '@migratable'
  - '@base'
  - '@namespaced'
  - '@described'
  - '@identifiable-stored'
  - '@metadatable'
  - '@named'
  - '@timeable'

# Indexes
indexes:
- - namespace
  - label

# Attributes
attributes:
  v1:
  - name: claims
    description: Contains the claims of the client that performed the import.
    type: list
    exposed: true
    subtype: string
    stored: true
    read_only: true
    autogenerated: true

  - name: constraint
    description: |-
      Define the import constraint. If Unrestricted, import
      can be deployed multiple times. If Unique, only one import is allowed
      in the current namespace and its child namespaces. If NamespaceUnique, only
      one import is allowed in the current namespace.
    type: enum
    exposed: true
    stored: true
    allowed_choices:
    - Unrestricted
    - Unique
    - NamespaceUnique
    default_value: Unrestricted

  - name: data
    description: Data to import.
    type: ref
    exposed: true
    subtype: export
    stored: true
    required: true
    example_value:
      externalnetworks:
      - associatedTags:
        - ext:net=tcp
        description: Represents all TCP traffic on any port
        entries:
        - 0.0.0.0/0
        name: all-tcp
        protocols:
        - tcp
      - associatedTags:
        - ext:net=udp
        description: Represents all UDP traffic on any port
        entries:
        - 0.0.0.0/0
        name: all-udp
        protocols:
        - udp
      networkaccesspolicies:
      - action: Allow
        description: Allows all communication from pu to pu, tcp and udp
        logsEnabled: true
        name: allow-all-communication
        object:
        - - $identity=processingunit
        - - ext:net=tcp
        - - ext:net=udp
        subject:
        - - $identity=processingunit
    extensions:
      refMode: pointer

  - name: label
    description: Label used for the imported data.
    type: string
    exposed: true
    stored: true
    autogenerated: true
