# Model
model:
  rest_name: installedapp
  resource_name: installedapps
  entity_name: InstalledApp
  package: highwind
  description: InstalledApps represents an installed application.
  aliases:
  - iapps
  - iapp
  get: true
  update: true
  delete: true

# Attributes
attributes:
  v1:
  - name: ID
    description: ID of the installed app.
    type: string
    exposed: true
    stored: true
    read_only: true
    autogenerated: true
    filterable: true
    format: free
    identifier: true
    primary_key: true

  - name: accountName
    description: AccountName represents the vince account name.
    type: string
    exposed: true
    stored: true
    creation_only: true
    format: free

  - name: categoryID
    description: CategoryID of the app.
    type: string
    exposed: true
    stored: true
    read_only: true
    filterable: true
    format: free
    orderable: true

  - name: currentVersion
    description: Version of the installed app.
    type: string
    exposed: true
    stored: true

  - name: data
    description: Data retains all data created to use this service.
    type: external
    subtype: service_data
    stored: true

  - name: k8sIdentifier
    description: K8SIdentifier retains the identifier for kubernetes.
    type: string
    stored: true
    format: free

  - name: name
    description: Name of the installed app.
    type: string
    exposed: true
    stored: true
    creation_only: true
    filterable: true
    format: free
    orderable: true

  - name: namespace
    description: Namespace in which the app is running.
    type: string
    exposed: true
    stored: true
    filterable: true
    format: free
    orderable: true

  - name: parameters
    description: Parameters is a list of parameters to start the app.
    type: external
    exposed: true
    subtype: app_parameters
    stored: true

  - name: relatedObjects
    description: RelatedObjects retains all objects created to use this app.
    type: external
    subtype: app_relatedobjects
    stored: true

  - name: status
    description: Status of the app.
    type: enum
    exposed: true
    stored: true
    read_only: true
    allowed_choices:
    - Error
    - Pending
    - Running
    default_value: Pending
    filterable: true
    orderable: true

# Relations
relations:
- rest_name: log
  descriptions:
    get: Returns the logs for a app.
  get: true
