# Model
model:
  rest_name: ipinfo
  resource_name: ipinfos
  entity_name: IPInfo
  package: canyon
  group: visualization/depmaps
  description: Provides information about IP address resolution.

# Attributes
attributes:
  v1:
  - name: IP
    description: The IP address.
    type: string
    exposed: true
    read_only: true
    autogenerated: true

  - name: error
    description: Error that occurred during resolution.
    type: string
    exposed: true
    read_only: true
    autogenerated: true

  - name: records
    description: List of DNS records associated with the IP address.
    type: external
    exposed: true
    subtype: map[string]string
    read_only: true
    autogenerated: true
