# Model
model:
  rest_name: log
  resource_name: logs
  entity_name: Log
  package: highwind
  group: integration/app
  description: Retrieves the logs of a deployed application.

# Attributes
attributes:
  v1:
  - name: data
    description: Contains all log data.
    type: external
    exposed: true
    subtype: map[string]string
    read_only: true
    autogenerated: true
