# Model
model:
  rest_name: pingrequest
  resource_name: pingrequests
  entity_name: PingRequest
  package: guy
  group: core/enforcer
  description: Initiates a ping request for defender debugging.

# Attributes
attributes:
  v1:
  - name: iterations
    description: Number of probes that will be triggered.
    type: integer
    exposed: true
    default_value: 1
    max_value: 20
    min_value: 1

  - name: pingID
    description: Unique ID generated for each ping request.
    type: string
    exposed: true
    read_only: true
    autogenerated: true

  - name: refreshID
    description: Contains the refresh ID set by processing unit refresh event.
    type: string
    exposed: true
    required: true
    example_value: xxxx-xxxx-xxxx
