# Model
model:
  rest_name: plan
  resource_name: plans
  entity_name: Plan
  package: vince
  group: core/billing
  description: Plan contains the various billing plans available.
  get:
    description: Retrieves the object with the given ID.

# Attributes
attributes:
  v1:
  - name: description
    description: Description contains the description of the Plan.
    type: string
    exposed: true
    stored: true
    read_only: true
    autogenerated: true

  - name: key
    description: Key contains the key identifier of the Plan.
    type: string
    exposed: true
    stored: true
    read_only: true
    autogenerated: true

  - name: name
    description: Name contains the name of the Plan.
    type: string
    exposed: true
    stored: true
    read_only: true
    autogenerated: true

  - name: quotas
    description: Quotas defines the quota for each identity.
    type: external
    subtype: map[string]int
    read_only: true
    autogenerated: true

  - name: requireAdminValidation
    description: RequireAdminValidation indicates if the plan requires an admin approval.
    type: boolean
    stored: true
    read_only: true
    autogenerated: true

  - name: roles
    description: Roles defines the roles given to the account.
    type: list
    subtype: string
    read_only: true
    autogenerated: true
