# Model
model:
  rest_name: plan
  resource_name: plans
  entity_name: Plan
  package: vince
  group: core/billing
  description: Contains the various billing plans available.
  get:
    description: Retrieves the plan with the given ID.

# Attributes
attributes:
  v1:
  - name: description
    description: Contains the description of the plan.
    type: string
    exposed: true
    stored: true
    read_only: true
    autogenerated: true

  - name: key
    description: Contains the key identifier of the plan.
    type: string
    exposed: true
    stored: true
    read_only: true
    autogenerated: true

  - name: name
    description: Contains the name of the plan.
    type: string
    exposed: true
    stored: true
    read_only: true
    autogenerated: true

  - name: quotas
    description: Defines the quota for each identity.
    type: external
    subtype: map[string]int
    read_only: true
    autogenerated: true

  - name: requireAdminValidation
    description: RequireAdminValidation indicates if the plan requires an admin approval.
    type: boolean
    stored: true
    read_only: true
    autogenerated: true

  - name: roles
    description: Roles defines the roles given to the account.
    type: list
    subtype: string
    read_only: true
    autogenerated: true
