# Model
model:
  rest_name: processingunit
  resource_name: processingunits
  entity_name: ProcessingUnit
  package: squall
  group: core/processingunit
  description: |-
    A Processing Unit reprents anything that can compute. It can be a Docker
    container, or a simple Unix process. They are created, updated and deleted by
    the system as they come and go. You can only modify its tags.  Processing Units
    use Network Access Policies to define which other Processing Units or External
    Services they can communicate with and File Access Policies to define what File
    Paths they can use.
  aliases:
  - pu
  - pus
  get:
    description: Retrieves the object with the given ID.
    global_parameters:
    - $archivable
  update:
    description: Updates the object with the given ID.
  delete:
    description: Deletes the object with the given ID.
    global_parameters:
    - $filtering
  extends:
  - '@archivable'
  - '@base'
  - '@described'
  - '@identifiable-stored'
  - '@metadatable'
  - '@named'
  - '@zonable'
  - '@timeable'

# Indexes
indexes:
- - namespace
  - operationalStatus
  - archived
- - namespace
  - normalizedTags
  - archived

# Attributes
attributes:
  v1:
  - name: collectInfo
    description: |-
      CollectInfo indicates to the enforcer it needs to collect information for this
      PU.
    type: boolean
    exposed: true
    stored: true

  - name: collectedInfo
    description: CollectedInfo represents the latest info collected by the enforcer
      for this PU.
    type: external
    exposed: true
    subtype: map[string]string
    stored: true

  - name: enforcementStatus
    description: EnforcementStatus communicates the state of the enforcer for that
      PU.
    type: enum
    exposed: true
    stored: true
    allowed_choices:
    - Active
    - Failed
    - Inactive
    default_value: Inactive
    filterable: true

  - name: enforcerID
    description: EnforcerID is the ID of the enforcer associated with the processing
      unit.
    type: string
    exposed: true
    stored: true
    filterable: true

  - name: enforcerNamespace
    description: |-
      enforcerNamespace is the namespace of the enforcer associated with the
      processing unit.
    type: string
    exposed: true
    stored: true
    filterable: true

  - name: image
    description: |-
      This field is deprecated and it is there for backward compatibility. Use
      `images` instead.
    type: string
    exposed: true
    deprecated: true

  - name: images
    description: List of images or executable paths used by the Processing Unit.
    type: list
    exposed: true
    subtype: string
    stored: true
    deprecated: true
    filterable: true

  - name: lastCollectionTime
    description: |-
      LastCollectionTime represents the date and time when the info have been
      collected.
    type: time
    exposed: true
    stored: true

  - name: lastPokeTime
    description: Last poke is the time when the pu got last poked.
    type: time
    stored: true

  - name: lastSyncTime
    description: LastSyncTime is the time when the policy was last resolved.
    type: time
    exposed: true
    stored: true
    autogenerated: true
    orderable: true

  - name: nativeContextID
    description: NativeContextID is the Docker UUID or service PID.
    type: string
    exposed: true
    stored: true

  - name: networkServices
    description: |-
      NetworkServices is the list of services that this processing unit has declared
      that it will be listening to. This can happen either with an activation command
      or by exposing the ports in a container manifest.
    type: refList
    exposed: true
    subtype: processingunitservice
    stored: true
    orderable: true
    validations:
    - $processingunitservices
    extensions:
      refMode: pointer

  - name: operationalStatus
    description: OperationalStatus of the processing unit.
    type: enum
    exposed: true
    stored: true
    allowed_choices:
    - Initialized
    - Paused
    - Running
    - Stopped
    - Terminated
    - Unknown
    default_value: Initialized
    filterable: true

  - name: tracing
    description: Tracing indicates if this PU must be placed in tracing mode.
    type: ref
    exposed: true
    subtype: tracemode
    stored: true
    extensions:
      refMode: pointer

  - name: type
    description: Type of the container ecosystem.
    type: enum
    exposed: true
    stored: true
    creation_only: true
    allowed_choices:
    - APIGateway
    - Docker
    - Host
    - HostService
    - LinuxService
    - RKT
    - User
    - SSHSession
    example_value: Docker
    filterable: true

# Relations
relations:
- rest_name: poke
  get:
    description: |-
      Sends a poke empty object. This will send a snaphot of the pu to time series
      database.
    parameters:
      entries:
      - name: enforcementStatus
        description: If set, changes the enforcement status of the processing unit
          alongside with the poke.
        type: enum
        allowed_choices:
        - Failed
        - Inactive
        - Active

      - name: forceFullPoke
        description: If set, it will trigger a full poke (slower).
        type: boolean

      - name: notify
        description: Can be sent to trigger a ProcessingUnitRefresh event that will
          be handled by the enforcer. If this is set, all other additional parameters
          will be ignored.
        type: boolean

      - name: status
        description: If set, changes the status of the processing unit alongside with
          the poke.
        type: enum
        allowed_choices:
        - Initialized
        - Paused
        - Running
        - Stopped
        example_value: Running

      - name: ts
        description: time of report. If not set, local server time will be used.
        type: time

- rest_name: renderedpolicy
  get:
    description: Retrieves the policies for the processing unit.
    parameters:
      entries:
      - name: csr
        description: CSR to sign.
        type: string
        example_value: |-
          --- BEGIN CSR ---
          xxx-xxx-xxx-xxx
          --- END CSR ---

- rest_name: service
  get:
    description: Retrieves the services used by a processing unit.

- rest_name: vulnerability
  get:
    description: Retrieves the vulnerabilities affecting the processing unit.
