# Model
model:
  rest_name: quotacheck
  resource_name: quotacheck
  entity_name: QuotaCheck
  package: squall
  group: policy/quota
  description: |-
    This api allows to verify the quota for a given identity in a given namespace
    with the given tags.

# Attributes
attributes:
  v1:
  - name: quota
    description: Contains the maximum number of matching entities that can be created.
    type: integer
    exposed: true
    read_only: true
    autogenerated: true

  - name: targetIdentity
    description: The identity name of the object you want to check the quota on.
    type: string
    exposed: true
    required: true
    example_value: processingunit

  - name: targetNamespace
    description: The namespace from which you want to check the quota on.
    type: string
    exposed: true
    example_value: /my/namespace
