# Model
model:
  rest_name: reportsquery
  resource_name: reportsqueries
  entity_name: ReportsQuery
  package: jenova
  group: visualization/reportsquery
  description: |-
    Supports querying Aporeto reports. All queries are protected within the
    namespace of the user.
  aliases:
  - rq

# Attributes
attributes:
  v1:
  - name: descending
    description: If set, the results will be ordered by time from the most recent
      to the oldest.
    type: boolean
    exposed: true

  - name: fields
    description: |-
      List of fields to extract. If you don't pass anything, all available fields will
      be selected.
    type: list
    exposed: true
    subtype: string

  - name: filter
    description: Apply a filter to the query.
    type: string
    exposed: true

  - name: groups
    description: |-
      Group results by the provided values. Note that not all fields can be used to
      group the results.
    type: list
    exposed: true
    subtype: string

  - name: limit
    description: Limits the number of results. `-1` means no limit.
    type: integer
    exposed: true
    default_value: -1

  - name: offset
    description: Offsets the results. -1 means no offset.
    type: integer
    exposed: true
    default_value: -1

  - name: report
    description: Name of the report type to query.
    type: enum
    exposed: true
    allowed_choices:
    - Flows
    - Audit
    - Enforcers
    - Files
    - EventLogs
    - Packets
    - EnforcerTraces
    - Counters
    - Accesses
    - DNSLookups
    - PingReports
    default_value: Flows

  - name: results
    description: Contains the result of the query.
    type: refList
    exposed: true
    subtype: reportsqueryresults
    read_only: true
    autogenerated: true
    extensions:
      refMode: pointer
