# Model
model:
  rest_name: role
  resource_name: roles
  entity_name: Role
  package: cid
  group: policy/authorization
  description: Returns the available roles that can be used with API authorizations.

# Attributes
attributes:
  v1:
  - name: authorizations
    description: Authorizations of the role.
    type: external
    exposed: true
    subtype: map[string][]string
    read_only: true
    autogenerated: true

  - name: description
    description: Description of the role.
    type: string
    exposed: true
    read_only: true
    autogenerated: true

  - name: key
    description: Key of the role.
    type: string
    exposed: true
    read_only: true
    autogenerated: true

  - name: name
    description: Name of the role.
    type: string
    exposed: true
    read_only: true
    autogenerated: true

  - name: private
    description: Set to `true` to make the role private and hidden from the UI.
    type: boolean
    exposed: true
    read_only: true
    autogenerated: true
