# Model
model:
  rest_name: role
  resource_name: roles
  entity_name: Role
  package: squall
  group: policy/authorization
  description: |-
    Roles returns the available roles that can be used with API Authorization
    Policies.

# Attributes
attributes:
  v1:
  - name: authorizations
    description: Authorizations of the role.
    type: external
    exposed: true
    subtype: map[string][]string
    read_only: true
    autogenerated: true

  - name: description
    description: Description is the description of the role.
    type: string
    exposed: true
    read_only: true
    autogenerated: true

  - name: key
    description: Key is the of the role.
    type: string
    exposed: true
    read_only: true
    autogenerated: true

  - name: name
    description: Name of the role.
    type: string
    exposed: true
    read_only: true
    autogenerated: true
