# Model
model:
  rest_name: tabulation
  resource_name: tabulations
  entity_name: Tabulation
  package: elena
  group: core/monitoring
  description: |-
    Allows you to retrieve a custom table view for any identity using
    any tags you like as columns.
  aliases:
  - table
  - tables
  - tabs
  - tab

# Attributes
attributes:
  v1:
  - name: headers
    description: Contains the requests headers that matched.
    type: list
    exposed: true
    subtype: string
    read_only: true
    autogenerated: true

  - name: rows
    description: Contains the tabulated data.
    type: external
    exposed: true
    subtype: '[][]interface{}'
    read_only: true
    autogenerated: true

  - name: targetIdentity
    description: Contains the requested target identity.
    type: string
    exposed: true
    read_only: true
    autogenerated: true
