# Model
model:
  rest_name: tag
  resource_name: tags
  entity_name: Tag
  package: tagle
  group: core/tag
  description: |-
    A tag is a key-value pair in string form that can applied to all objects in
    the system. They are used for policy resolution. Tags starting with `$` are
    derived from the property of an object. For example an object with an ID set to
    `xxx` and a name set to `the name` will be tagged by default with `$name=the name`
    and `$id=xxx`. Tags starting with an `@` have been generated by an external
    system.
  extends:
  - '@namespaced'
  - '@identifiable-stored'

# Attributes
attributes:
  v1:
  - name: count
    description: Represents the number of times the tag is used.
    type: integer
    exposed: true
    stored: true
    read_only: true
    autogenerated: true

  - name: value
    description: Represents the value of the tag.
    type: string
    exposed: true
    stored: true
    required: true
    creation_only: true
    example_value: key=value
    validations:
    - $tag
