# Model
model:
  rest_name: trustednamespace
  resource_name: trustednamespaces
  entity_name: TrustedNamespace
  package: squall
  group: policy/enforcerconfig
  description: |-
    This object allows you to declare trust between namespaces that are cryptographically
    isolated. The namespaces can be local or served by different Segment Console controllers.
  aliases:
  - trustedns
  get:
    description: Retrieve the trusted namespace with the given ID.
  update:
    description: Update the trusted namespace with the given ID.
  delete:
    description: Delete the trusted namespace with the given ID.
  extends:
  - '@zoned'
  - '@migratable'
  - '@base'
  - '@namespaced'
  - '@identifiable-stored'
  - '@named'
  - '@timeable'

# Attributes
attributes:
  v1:
  - name: certificateAuthority
    description: Contains the PEM block of the certificate authority trusted namespace.
    type: string
    exposed: true
    stored: true
    example_value: |-
      -----BEGIN CERTIFICATE-----
      MIIBbjCCARSgAwIBAgIRANRbvVzTzBZOvMCb8BiKCLowCgYIKoZIzj0EAwIwJjEN
      MAsGA1UEChMEQWNtZTEVMBMGA1UEAxMMQWNtZSBSb290IENBMB4XDTE4MDExNTE4
      NDgwN1oXDTI3MTEyNDE4NDgwN1owJjENMAsGA1UEChMEQWNtZTEVMBMGA1UEAxMM
      QWNtZSBSb290IENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEJ/80HR51+vau
      7XH7zS7b8ABA0e/TdBOg1NznbnXdXil1tDvWloWuH5+/bbaiEg54wksJHFXaukw8
      jhTLU7zT56MjMCEwDgYDVR0PAQH/BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wCgYI
      KoZIzj0EAwIDSAAwRQIhALwAZh2KLFFC1qfb5CqFHExlXS0PUltax9PvQCN9P0vl
      AiBl7/st9u/JpERjJgirxJxOgKNlV6pq9ti75EfQtZZcQA==
      -----END CERTIFICATE-----
    validations:
    - $capem

  - name: propagate
    description: Propagates the object to all of its children.
    type: boolean
    exposed: true
    stored: true
    read_only: true
    autogenerated: true
    default_value: true
    getter: true
    setter: true
    transient: true

  - name: remoteController
    description: The controller declared in the certificate authority.
    type: string
    exposed: true
    stored: true
    read_only: true
    autogenerated: true

  - name: remoteNamespace
    description: The namespace declared in the certificate authority.
    type: string
    exposed: true
    stored: true
    read_only: true
    autogenerated: true

  - name: serialNumber
    description: The serial number of the CA.
    type: string
    exposed: true
    stored: true
    read_only: true
    autogenerated: true
