{
    "attributes": [
        {
            "allowed_chars": null,
            "allowed_choices": null,
            "autogenerated": null,
            "channel": null,
            "creation_only": null,
            "default_order": null,
            "default_value": null,
            "deprecated": null,
            "description": "AWSAccountID contains your verified accound id.",
            "exposed": true,
            "filterable": true,
            "foreign_key": null,
            "format": "free",
            "getter": null,
            "identifier": null,
            "index": null,
            "max_length": null,
            "max_value": null,
            "min_length": null,
            "min_value": null,
            "name": "AWSAccountID",
            "orderable": true,
            "primary_key": null,
            "read_only": null,
            "required": null,
            "secret": null,
            "setter": null,
            "stored": true,
            "subtype": null,
            "transient": null,
            "type": "string",
            "unique": null,
            "uniqueScope": null
        }
    ],
    "children": [],
    "model": {
        "aliases": [
            "aws",
            "awsaccs",
            "awsacc"
        ],
        "create": null,
        "delete": true,
        "description": "Allows to bind an AWS account to your Aporeto account to allow auto registration of enforcers running on EC2 ",
        "entity_name": "AWSAccount",
        "extends": [],
        "get": true,
        "package": null,
        "resource_name": "awsaccounts",
        "rest_name": "awsaccount",
        "root": null,
        "update": true
    }
}