package squallmodels

import "fmt"
import "github.com/aporeto-inc/elemental"

import "sync"

// ExternalAccessIdentity represents the Identity of the object
var ExternalAccessIdentity = elemental.Identity{
	Name:     "externalaccess",
	Category: "externalaccesses",
}

// ExternalAccessList represents a list of ExternalAccess
type ExternalAccessList []*ExternalAccess

// ContentIdentity returns the identity of the objects in the list.
func (o ExternalAccessList) ContentIdentity() elemental.Identity {

	return ExternalAccessIdentity
}

// List converts the object to an elemental.IdentifiablesList.
func (o ExternalAccessList) List() elemental.IdentifiablesList {

	out := elemental.IdentifiablesList{}
	for _, item := range o {
		out = append(out, item)
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o ExternalAccessList) DefaultOrder() []string {

	return []string{}
}

// ExternalAccess represents the model of a externalaccess
type ExternalAccess struct {
	// IPs list all addresses
	IPs []string `json:"IPs" bson:"-"`

	// externalService contains the associated external service information
	ExternalService *ExternalService `json:"externalService" bson:"-"`

	ModelVersion float64 `json:"-" bson:"_modelversion"`

	sync.Mutex
}

// NewExternalAccess returns a new *ExternalAccess
func NewExternalAccess() *ExternalAccess {

	return &ExternalAccess{
		ModelVersion: 1.0,
	}
}

// Identity returns the Identity of the object.
func (o *ExternalAccess) Identity() elemental.Identity {

	return ExternalAccessIdentity
}

// Identifier returns the value of the object's unique identifier.
func (o *ExternalAccess) Identifier() string {

	return ""
}

// SetIdentifier sets the value of the object's unique identifier.
func (o *ExternalAccess) SetIdentifier(ID string) {

}

// Version returns the hardcoded version of the model
func (o *ExternalAccess) Version() float64 {

	return 1.0
}

// DefaultOrder returns the list of default ordering fields.
func (o *ExternalAccess) DefaultOrder() []string {

	return []string{}
}

// Doc returns the documentation for the object
func (o *ExternalAccess) Doc() string {
	return `ExternalAccess allows to retrieve connection from or to an external service`
}

func (o *ExternalAccess) String() string {

	return fmt.Sprintf("<%s:%s>", o.Identity().Name, o.Identifier())
}

// Validate valides the current information stored into the structure.
func (o *ExternalAccess) Validate() error {

	errors := elemental.Errors{}
	requiredErrors := elemental.Errors{}

	if len(requiredErrors) > 0 {
		return requiredErrors
	}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (*ExternalAccess) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	if v, ok := ExternalAccessAttributesMap[name]; ok {
		return v
	}

	// We could not find it, so let's check on the lower case indexed spec map
	return ExternalAccessLowerCaseAttributesMap[name]
}

// AttributeSpecifications returns the full attribute specifications map.
func (*ExternalAccess) AttributeSpecifications() map[string]elemental.AttributeSpecification {

	return ExternalAccessAttributesMap
}

// ExternalAccessAttributesMap represents the map of attribute for ExternalAccess.
var ExternalAccessAttributesMap = map[string]elemental.AttributeSpecification{
	"IPs": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		Description:    `IPs list all addresses`,
		Exposed:        true,
		Name:           "IPs",
		ReadOnly:       true,
		SubType:        "string",
		Type:           "list",
	},
	"ExternalService": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		Description:    `externalService contains the associated external service information`,
		Exposed:        true,
		Name:           "externalService",
		ReadOnly:       true,
		SubType:        "external_service",
		Type:           "external",
	},
}

// ExternalAccessLowerCaseAttributesMap represents the map of attribute for ExternalAccess.
var ExternalAccessLowerCaseAttributesMap = map[string]elemental.AttributeSpecification{
	"ips": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		Description:    `IPs list all addresses`,
		Exposed:        true,
		Name:           "IPs",
		ReadOnly:       true,
		SubType:        "string",
		Type:           "list",
	},
	"externalservice": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		Description:    `externalService contains the associated external service information`,
		Exposed:        true,
		Name:           "externalService",
		ReadOnly:       true,
		SubType:        "external_service",
		Type:           "external",
	},
}
