package squallmodels

import "fmt"
import "github.com/aporeto-inc/elemental"

import "sync"

// SyscallAccessIdentity represents the Identity of the object
var SyscallAccessIdentity = elemental.Identity{
	Name:     "syscallaccess",
	Category: "syscallaccesses",
}

// SyscallAccessList represents a list of SyscallAccess
type SyscallAccessList []*SyscallAccess

// ContentIdentity returns the identity of the objects in the list.
func (o SyscallAccessList) ContentIdentity() elemental.Identity {

	return SyscallAccessIdentity
}

// List converts the object to an elemental.IdentifiablesList.
func (o SyscallAccessList) List() elemental.IdentifiablesList {

	out := elemental.IdentifiablesList{}
	for _, item := range o {
		out = append(out, item)
	}

	return out
}

// DefaultOrder returns the default ordering fields of the content.
func (o SyscallAccessList) DefaultOrder() []string {

	return []string{}
}

// SyscallAccess represents the model of a syscallaccess
type SyscallAccess struct {
	// PID is the PID of the process that used the system call.
	PID int `json:"PID" bson:"-"`

	// Actions tells if the system call has been allowed.
	Action string `json:"action" bson:"-"`

	// Count tells how many times the syscall has been sent.
	Count int `json:"count" bson:"-"`

	// Name represents the name of the system call.
	Name string `json:"name" bson:"-"`

	// ProcessName is the name of the process that used the system call.
	ProcessName string `json:"processName" bson:"-"`

	// Propagate indicates that the policy must be propagated to the children namespaces.
	Propagate bool `json:"propagate" bson:"-"`

	ModelVersion float64 `json:"-" bson:"_modelversion"`

	sync.Mutex
}

// NewSyscallAccess returns a new *SyscallAccess
func NewSyscallAccess() *SyscallAccess {

	return &SyscallAccess{
		ModelVersion: 1.0,
		Propagate:    false,
	}
}

// Identity returns the Identity of the object.
func (o *SyscallAccess) Identity() elemental.Identity {

	return SyscallAccessIdentity
}

// Identifier returns the value of the object's unique identifier.
func (o *SyscallAccess) Identifier() string {

	return ""
}

// SetIdentifier sets the value of the object's unique identifier.
func (o *SyscallAccess) SetIdentifier(ID string) {

}

// Version returns the hardcoded version of the model
func (o *SyscallAccess) Version() float64 {

	return 1.0
}

// DefaultOrder returns the list of default ordering fields.
func (o *SyscallAccess) DefaultOrder() []string {

	return []string{}
}

// Doc returns the documentation for the object
func (o *SyscallAccess) Doc() string {
	return nodocString
}

func (o *SyscallAccess) String() string {

	return fmt.Sprintf("<%s:%s>", o.Identity().Name, o.Identifier())
}

// Validate valides the current information stored into the structure.
func (o *SyscallAccess) Validate() error {

	errors := elemental.Errors{}
	requiredErrors := elemental.Errors{}

	if len(requiredErrors) > 0 {
		return requiredErrors
	}

	if len(errors) > 0 {
		return errors
	}

	return nil
}

// SpecificationForAttribute returns the AttributeSpecification for the given attribute name key.
func (*SyscallAccess) SpecificationForAttribute(name string) elemental.AttributeSpecification {

	return SyscallAccessAttributesMap[name]
}

// AttributeSpecifications returns the full attribute specifications map.
func (*SyscallAccess) AttributeSpecifications() map[string]elemental.AttributeSpecification {

	return SyscallAccessAttributesMap
}

// SyscallAccessAttributesMap represents the map of attribute for SyscallAccess.
var SyscallAccessAttributesMap = map[string]elemental.AttributeSpecification{
	"PID": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		Description:    `PID is the PID of the process that used the system call.`,
		Exposed:        true,
		Name:           "PID",
		ReadOnly:       true,
		Type:           "integer",
	},
	"Action": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		Description:    `Actions tells if the system call has been allowed.`,
		Exposed:        true,
		Format:         "free",
		Name:           "action",
		ReadOnly:       true,
		Type:           "string",
	},
	"Count": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		Description:    `Count tells how many times the syscall has been sent.`,
		Exposed:        true,
		Name:           "count",
		ReadOnly:       true,
		Type:           "integer",
	},
	"Name": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		Description:    `Name represents the name of the system call.`,
		Exposed:        true,
		Format:         "free",
		Name:           "name",
		ReadOnly:       true,
		Type:           "string",
	},
	"ProcessName": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		Autogenerated:  true,
		Description:    `ProcessName is the name of the process that used the system call.`,
		Exposed:        true,
		Format:         "free",
		Name:           "processName",
		ReadOnly:       true,
		Type:           "string",
	},
	"Propagate": elemental.AttributeSpecification{
		AllowedChoices: []string{},
		DefaultValue:   false,
		Description:    `Propagate indicates that the policy must be propagated to the children namespaces.`,
		Exposed:        true,
		Filterable:     true,
		Name:           "propagate",
		Orderable:      true,
		Type:           "boolean",
	},
}
